### ISSUE TITLE
manupulators aren't deleted after object deletion

### ISSUE THREAD

**Issue by vvoovv** [s-leger/archipack#1]
I created a window
Then pressed _Delete_ button in the properties panel.
The window disappeared, but the manipulators were still there

**Comment by s-leger** [comment]
Hi, 
Thank you for reporting this issue.
Manipulator operator exit condition should be fixed.

**Comment by mirlip** [comment]
for me this bug still happens with latest version.

**Comment by s-leger** [comment]
Hmm can't repro.
Did you use non standard shortcut for delete ? 
Code is looking in user prefs to retrieve right shortcut, maybe something wrong here.

```python
        # clean up manipulator on delete
        if self.keymap.check(event, self.keymap.delete):  # {'X'}:
            self.manipulable_disable(context)

            if bpy.ops.object.delete.poll():
                bpy.ops.object.delete('INVOKE_DEFAULT', use_global=False)

            return {'FINISHED'}

```

**Comment by mirlip** [comment]
I tested with a fresh buildbot and factory settings, same problem, manipulators stay.
If I undo back to default cube after adding a window and then try to add a window again it crashes: 
- add a window (not the draw operator), hit ctrl+Z twice. The first time it removes the manipulators, the second time the window. 
- Then try to add a window again, it crashes.

It also crashes if I start a new file and then try to add another window.

**Comment by s-leger** [comment]
Ok,
both confirmed, found root source and fixed.
Buildbot version currently not lastest, 
will commit preset_menu branch (lastest) on it as soon as i find a clean way to reparent windows and doors.
