### ISSUE TITLE
preset system doesn't update and get's broken by interactive mode.

### ISSUE THREAD

**Issue by mirlip** [s-leger/archipack#10]
Hi @s-leger, just tried the new preset system and found 2 problems.
I selected a window, modified some settings, clicked on the plus near the styles, named it test. Selected another window, selected 'test' in the dropdown menu but nothing happens.
One time it somehow worked, but then, as I clicked 'interactive' for the wall, it removed the style.

**Comment by s-leger** [comment]
Preset system only store style related variables, not width, height not depth.
Can't repro your problem here, seem to work as expected.
Check which param do blender store in your 
%User%/AppData/(Local/Roaming)/Blender Foundation/scripts/presets/archipack_window/stylename.py

should be something like:

```python
import bpy
d = bpy.context.active_object.data.archipack_window[0]

d.out_frame_y = 0.06999999284744263
d.warning = False
d.in_tablet_enable = True
d.blind_z = 0.029999999329447746
d.elipsis_b = 0.5
d.flip = False
d.hole_margin = 0.10000000149011612
d.rows.clear()
item_sub_1 = d.rows.add()
item_sub_1.name = ''
item_sub_1.width = (50.0, 50.0, 50.0, 50.0, 50.0, 50.0, 50.0, 50.0, 50.0, 50.0, 50.0, 50.0, 50.0, 50.0, 50.0, 50.0, 50.0, 50.0, 50.0, 50.0, 50.0, 50.0, 50.0, 50.0, 50.0, 50.0, 50.0, 50.0, 50.0, 50.0, 50.0)
item_sub_1.fixed = (False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False)
item_sub_1.n_cols = 2
item_sub_1.auto_update = True
item_sub_1.cols = 2
item_sub_1.height = 1.0
d.n_rows = 1
d.in_tablet_x = 0.03999999910593033
d.out_frame_offset = 0.0
d.out_tablet_x = 0.16999998688697815
d.out_tablet_z = 0.029999999329447746
d.handle_altitude = 1.399999976158142
d.offset = 0.10000000149011612
d.in_tablet_y = 0.03999999910593033
d.handle_enable = True
d.out_tablet_y = 0.16999998688697815
d.blind_open = 80.0
d.curve_steps = 16
d.window_type = 'FLAT'
d.frame_x = 0.05999999865889549
d.out_frame = True
d.angle_y = 0.0
d.frame_y = 0.05999999865889549
d.in_tablet_z = 0.029999999329447746
d.blind_y = 0.0020000000949949026
d.out_frame_x = 0.10000000149011612
d.out_tablet_enable = True
d.radius = 2.5
d.blind_enable = True
```

**Comment by mirlip** [comment]
ok, just made the test, it works to link with ctrl+L to different windows. I thought it would only link the selected mesh and not the other ones (as a window for example is made of several meshes). So it's great to have links for 100% identical objects and styles for having different objects share a look.

But then we would definitely need to store the material name in the style to allow different materials for different windows. The boolean object could also have a material set in the style to allow to have window/doors openings of a different color than the rest of the facade.

**Comment by s-leger** [comment]
Window and door take care of linking sub mesh when "refresh" is pressed and when editing parameters if a sub is missing, as this is needed to auto update all sub meshes when changing parent.
When parent width/depth does change, the base object also take care of make location consistent across subs, so any sub rotation is preserved while editing.

This allow different materials for linked objects, as materials on the object / subs are not linked. 

The point with storing material name is sharing between different projects, where not all materials are there.

Storing materials ids lead to linked ids too, but may be an option to store style.
Doing this way, if i add say "plastic" "wood" "alu" to window default material, and store material id on style, choosing a style define base aspect, and override on object materials allow variations.

Hole is generated when needed (each boolean press, params editing), and hole object may be deleted in the between when wall's openings count does change. So having configurable material ids for holes may help, with 2 or 3 alternate materials added to base material to switch from. 
Overriding materials here not an option given the object maybe being deleted in the between.

Having tools like np_station shader brush here may help in styling across objects.
A "share material with selection" button may also be helpfull.
