### ISSUE TITLE
Grease Pencil laggy when archipack enabled

### ISSUE THREAD

**Issue by yebyte** [s-leger/archipack#104]
Archipack version: 2.0.5

Blender version: Blender 2.8.0 2019-04-07 15:02

Os version: Windows 10 1809 & Ubuntu 18.04 LTS

Description of the issue: I use Blender 2.8 on my Surface Pro 5 and desktop with Wacom Intuos Pro M.  This issue seems to be device independemt. When Archipack is enabled, it is very laggy in Draw Mode to draw a stroke and the stroke become very jaggy before post-processing. 
![screen](https://user-images.githubusercontent.com/33513348/55708098-aaee4380-5a17-11e9-9cb7-f9509d120528.png)

**Comment by s-leger** [comment]
Hi,
Thank you for reporting !
Unlike some other add-ons, Archipack does not interact with the scene at all unless an archipack object is selected. So i don't think it is the source of this issue. 
Any message in the system console (use window -> toggle system console) ?
Any other fancy "cutter / boolean / kit" add-on enabled too ?

**Comment by yebyte** [comment]
![screen](https://user-images.githubusercontent.com/33513348/55727158-f4548800-5a43-11e9-90d8-cacf5d82579e.png)
I'm pretty sure I disabled all the other plug-ins. First time i disabled all with Workspace - Filter Addons except Archipack.  Second time i deactivated all in Preferences - Add-ons. I toggled Archipack on and off in this two ways. And then I came to this conclusion.

**Comment by yebyte** [comment]
![Snipaste_2019-04-08_21-24-57](https://user-images.githubusercontent.com/33513348/55727765-43e78380-5a45-11e9-9410-ea8bff5983a3.png)
![Snipaste_2019-04-08_21-27-44](https://user-images.githubusercontent.com/33513348/55727766-43e78380-5a45-11e9-9941-9f94777313b1.png)
Messages in the system console when i create a 2D Animation blend file.

**Comment by s-leger** [comment]
Yes great,
Looks like i'm able to provide a fix for this issue, will be in 2.0.6

Thank you !

**Comment by yebyte** [comment]
> 
> 
> Yes great,
> Looks like i'm able to provide a fix for this issue, will be in 2.0.6
> 
> Thank you !

Thank you for your quick reply. Hope it gets better and better.
