### ISSUE TITLE
Blender crashes on wall creation

### ISSUE THREAD

**Issue by advancingu** [s-leger/archipack#105]
Archipack version: 2.0.6 Pro

Blender version: 2.80-ddb71e8c20c2 daily build

OS version: Ubuntu 19.04

Description of the issue:
In the cube default scene, try to draw any preset wall type. As soon as the preset is selected, Blender crashes. Blender also now crashes when selecting a wall in an existing scene that was created with Blender 2.80-480a09a92f7f and Archipack 2.0.6 where things were working fine.

I already tried removing and reinstalling Archipack as suggested in #101 but the crashes remain.

Probably some Blender API got changed in the past days before the API freeze next week. I look forward to receiving a fixed build of Archipack.

**Comment by s-leger** [comment]
Thank you for reporting.
Building from scratch using lastest git sources here, and unable to repro in that version. 
This issue is probably related to linux 480a09a92f7f buildbot version and also confirmed under windows bfef3bce1a93 and should be fixed by next buildbot version.

**Comment by advancingu** [comment]
Working again with 2.80-3dc9da3a74ee. Thanks!
