### ISSUE TITLE
Moving wall altitude breaks wall finish

### ISSUE THREAD

**Issue by AdrParkinson** [s-leger/archipack#107]
Archipack version: 2.0.7

Blender version: 2.80 2019-05-14

Os version: Windows 10 Home

Description of the issue: I have a project where I need to move the main wall object below the default start point. When I do this, it causes the wall finish to become much thicker than it is supposed to be. See below:
<a href="https://imgur.com/57qS9MG"><img src="https://i.imgur.com/57qS9MG.jpg" title="source: imgur.com" /></a>

**Comment by s-leger** [comment]
Hi, thank you for reporting !

Found and fixed the root of this issue, will be part of next release.
In the meantime, generate your wall at altitude 0 and then move the reference point according  https://youtu.be/2W1EQu28GPg

**Comment by AdrParkinson** [comment]
That was fast! This will make my life easier. I thought I was doing something wrong at first.

**Comment by s-leger** [comment]
I keep this report open until 2.0.8 release so anyone facing with same issue is able to find a solution.
