### ISSUE TITLE
Door creation throws exceptions

### ISSUE THREAD

**Issue by advancingu** [s-leger/archipack#108]
Archipack version: 2.0.7

Blender version: 2.80-f070bdd7c9c4

Os version: Ubuntu 19.04

Description of the issue:
Placing a door on an interior wall triggers this exception in most cases:
![image](https://user-images.githubusercontent.com/130207/57808862-a0d10a80-7764-11e9-8e13-c63f94f21a9f.png)

**Comment by s-leger** [comment]
Hi, Thank you for reporting.
This error means one of your floor has a segment with a null length (0)
Either remove the null segment, or disable grout may solve this issue. 

You should only generate your floors after the openings so they are able to fill gaps under wall inside openings.

Fixed this bug and will be part of next release.

**Comment by advancingu** [comment]
Thanks for the quick response.

Usually I delete floors around a wall before I place any doors on it, so I'm not sure what else I could do. Also, how can I find the floor segments that have a zero length segment?

**Comment by s-leger** [comment]
When selected floor object does show the segment index (black number) at middle of segment. Try to find any of those numbers over a segment end (square handle). - probably near opening / opening close to an edge of a wall.

Could you share the file (walls + openings + reference point) so i'm able to investigate further as looks like it's a topological issue, leading to such wrong null segment generation.

**Comment by advancingu** [comment]
This is the file. There might be a number of issues, for example I had some rooms where floors were overlapping or clipping through walls, even though snapping was turned on. Note that this is approximating an existing house that is ~120 years old.
Edit: File removed.

**Comment by s-leger** [comment]
Looks like there are overlapping walls, this lead into floors generated below those parts.

Try to disable "Fast boolean" option ("slow boolean" was enhanced in 2.0.7 and is 10x faster so there is nearly no advantages to use fast one, and "slow" is much safer) - select all floors and with alt pressed uncheck "Fast boolean" at bottom of main Flooring panel.

You may also remove any "Floor cutter" not child of a "Floor" object - they are no more needed.

**Comment by s-leger** [comment]
Released 2.0.8 today
