### ISSUE TITLE
Error while adding irradiance volume

### ISSUE THREAD

**Issue by thegaryishere** [s-leger/archipack#109]
![archipack error](https://user-images.githubusercontent.com/47903990/58433748-32eae400-807e-11e9-89ba-d77bcd520940.jpg)
Archipack version: 2.07

Blender version: blender-2.80-f18373a9ab1a-win64

Os version: Win 10 pro

Description of the issue: Error while adding irradiance volume

**Comment by s-leger** [comment]
Hi, thank you for reporting,
this is a known issue with recent API changes.
- presets thumbs are not working
- both irradiance volume and cubemaps are failing.

Will try to fix and push a new release as soon as possible, in the meantime, you should rely on manually add your irradiance volume.

**Comment by thegaryishere** [comment]
Thank you for the reply.
Gary

**Comment by thegaryishere** [comment]
They do work manually. I have done that in the meantime. 

Gary

**Comment by s-leger** [comment]
Released 2.0.8 today.
