### ISSUE TITLE
Blender crash to desktop on creating wall.

### ISSUE THREAD

**Issue by melkesedek** [s-leger/archipack#110]
Archipack version: 2.07

Blender version: blender-2.80.0-git.81b68f7279cd-windows64

Os version: Win 10 home

Description of the issue: Blender crash on creating wall. Crash to desktop.

**Comment by s-leger** [comment]
Hi,
There is a known issue with recent blender 2.8 builds, have a fix for it, but still in depth test phase so i can ensure it is not breaking anything else. Will provide 2.0.8 soon.
In the meantime, disable "Auto-manipulate".

**Comment by s-leger** [comment]
Released 2.0.8 today
