### ISSUE TITLE
Can't manipulate the handle on Windows platform

### ISSUE THREAD

**Issue by yebyte** [s-leger/archipack#112]
Archipack version: 2.08

Blender version: 2.80 (sub 74), branch: blender2.7, commit date: 2019-06-10 23:38, hash: a0608340ae14

Os version: Windows 1903

Description of the issue: I use the latest build of Blender 2.80. When Auto Manipulate enabled. it shows the handle, but i can't click and drag to adjust them. But it works fine in Blender on Linux.

**Comment by yebyte** [comment]
Archipack version: 2.08

Blender version: 2.80 (sub 74), branch: blender2.7, commit date: 2019-06-10 23:38, hash: a0608340ae14

Os version: Windows 1903 Ubuntu 18.04 LTS
Description of the issue: Archipack behaves unexpected when Draw a Wall use 3dsmax Style is disabled. When i draw the first segment, i click and click to confirm one segment, then begin the second segment, i can't finish the drawing process until i press esc or right click.

**Comment by s-leger** [comment]
Hi, 
Thank you for reporting.
Will investigate for your manipulate issue under windows platform.

There are known limitations in draw a wall when "Use 3dsmax style is" disabled.
You can't use the shortcuts, nor close your wall, and viewport navigation is locked.

**Comment by s-leger** [comment]
Pushed 2.0.9 on gurmorad, should fix your issue.
