### ISSUE TITLE
Save new preset stopped working

### ISSUE THREAD

**Issue by RaceCondition** [s-leger/archipack#115]
Archipack version: 2.0.8

Blender version: 2.80 beta

Os version: Linux Mint 19

Description of the issue:
Presets don't seem to be saving. I've tried Fence and Wall, usual activity of clicking on the + symbol and choosing a name but it does not save. I originally updated an existing preset by saving with the same name and then noticed it was gone.
It worked without a problem in 2.0.7.

**Comment by s-leger** [comment]
Hi, 
Are you using a recent build of blender ?
Some breaking API changes required to adapt the background render code according.

**Comment by RaceCondition** [comment]
Yeah, that was it. I thought I was on the latest by using Snap but the build is from March. I downloaded directly from blender.org and it works fine. My bad - I should have tried that before raising an issue.

**Comment by ArtBIT** [comment]
I am using Archipack PRO 2.3.1 in Blender 2.83.2 and I experience the same problem. I cannot save any presets. Does this mean that Blender 2.83 is not supported?

**Comment by s-leger** [comment]
Blender 2.83 is supported and recommanded version for archipack 2.3.1
Ensure you are using original add-on downloaded from blender-archipack.org
Please use "Create->About->Contact support" for support requests by mail for 2.x version

**Comment by mattkay11** [comment]
I am using Blender 2.8.3 and just bought the ArchiPack Pro version 2.3.3. today. I also cannot add presets.

**Comment by s-leger** [comment]
I'm unable to repro this error under 2.3.3, ensure archipack lite is disabled, restart blender, then setup 2.3.3

Please use "Create->About->Contact support" for support requests by mail for 2.x version
