### ISSUE TITLE
Autoboolean sometimes not working properly

### ISSUE THREAD

**Issue by TritiatedWater** [s-leger/archipack#116]
Archipack version:
2.0.10
Blender version:
blender-2.80-c0c1b4542f39-linux-glibc224-x86_64
Os version:
Linux Mint 19.1
Description of the issue:
inserting a window on a wall sometime the holes doesn't appear.
![Screenshot from 2019-06-25 17-35-59](https://user-images.githubusercontent.com/19777767/60092241-bf1d2380-9770-11e9-8d17-eac645b178d1.png)
[floo1r.blend.zip](https://github.com/s-leger/archipack/files/3324836/floo1r.blend.zip)

**Comment by s-leger** [comment]
Hi, looks like you are hitting blender's boolean limits here.
Try to add more segments to the wall object parameters, in axis tab, expand a segment then use insert button (+)

**Comment by TritiatedWater** [comment]
Still no luck. Got any more possible workarounds?

**Comment by s-leger** [comment]
Try to slightly move your windows on the z axis so the hole doesn't exactly fit with wall's bottom. 
By the way, is the "floor thickness" of your wall set to 0 ? 
if so try to set it to a small value like 1mm to fix this issue for next windows.

**Comment by TritiatedWater** [comment]
My floor thickness value is 0.1m, increasing it still won't work.
But increasing the wall thickness to 0.2m from 0.1m works.
