### ISSUE TITLE
Exception when deleting a newly created wall

### ISSUE THREAD

**Issue by aldanor** [s-leger/archipack#117]
Archipack version: 2.0.9
Blender version: 2.80b
Os version: OSX

If you create a wall and while still in "wall draw mode" press Delete to delete it, and then click anywhere in the viewport, it raises this exception:

![image](https://user-images.githubusercontent.com/2418513/60376098-79788900-9a04-11e9-9f82-e6f47068fb38.png)

**Comment by s-leger** [comment]
Hi,
This error probably is related to keymap changes in 2.8 (programmatic one), as the code should properly handle delete, but something is going wrong.

```python
        if self.keymap.check(event, self.keymap.delete):
            self.exit(context)
            return {'FINISHED', 'PASS_THROUGH'}
```

**Comment by s-leger** [comment]
Fixed, will be part of next release.
