### ISSUE TITLE
Adding new wall segments to existing wall set in 2.0

### ISSUE THREAD

**Issue by aldanor** [s-leger/archipack#118]
In v2.0, what's the most convenient way to add new segments to the existing wall set?

The "Reverse" has been removed (it existed in v1), so now you have to switch back from "Axis" tab back to "Main" tab, click "Flip In & Out" if you want to append to the other end (not the most obvious thing...), then click back to "Axis" mode, then click "+". And then repeat it again...

Also, for each segment the angle will likely be incorrect, so now you have to manually scroll through the list of segments below, open it, click on Angle, and enter the correct value.

It would be nice if the process was somewhat simpler... For example:
- Add "+" and "-" buttons to add/remove segments (similar to how it's done with slices)
- Add a button to reverse the order in Axis tab (why is it called "Axis" btw?)
- Show segments in reversed order - e.g. Seg 3, Seg 2, Seg1 - so that if you add a new segment it appears on top and you don't have to scroll
- In the segment list, show the last segment unfolded? So you don't have to click on triangle button every time to open its editor
- Maybe consider simplifying the process somehow by allowing to type in the length + angle of the segment to add (just a thought)

**Comment by s-leger** [comment]
Hi, 
You can add / remove segments right on screen at any time, select your wall to enable manipulators, then, use the small arrows located near the end of the last segment. 
You also may select the angle manipulator text to enter any value.
Wall do provide a "Draw tool" to create multi-segments walls using snap. So usually you should not need to add remove segments.

**Comment by aldanor** [comment]
If you're trying to model an exact floor plan with 50+ tightly packed wall segments, manipulators becomes useless as there's just a mess of arrows on screen, it's much easier to add "new segment", type in the angle and the dimensions.

It's just with the current UI you have to click a lot of buttons which makes it complicated...

**Comment by s-leger** [comment]
2.2.4 implements on screen add / remove segment manipulators so you no more need to go into the ui.
