### ISSUE TITLE
Floor moldings ignore floor thickness (2.0)

### ISSUE THREAD

**Issue by aldanor** [s-leger/archipack#119]
Create some walls -> create floor, set floor thickness to 50cm, add floor moldings -> they will be created below the floor. Looks like the generation procedure assumes the default floor thickness of 10cm always, is it to be expected?

It's not a huge problem since you can always move it, but sometimes floor thickness may differ, in which case it becomes more painful.

**Comment by s-leger** [comment]
Floor thickness should be defined in wall parameters.
The idea behind is that your finished floor level is always at 0 altitude, the bottom of the wall will move according.
Then creating moldings / floors from wall will use this thickness. - molding will always be at 0 altitude, and floor bottom and thickness will adjust to wall "floor thickness" so top of the floor also will be at 0 altitude.
If you have more than one floor thickness on your level, set the most used in wall parameters, then adjust other ones.

**Comment by aldanor** [comment]
Thanks, that makes sense, I'll close this one then.
