### ISSUE TITLE
correct windows height in interactive mode

### ISSUE THREAD

**Issue by mirlip** [s-leger/archipack#12]
Interactive mode at the moment aligns windows to walls, which is really great, but height is left. It results in the actual height beeing different from the displayed height in UI. Best would be to adjust the height to start from the floor instead of the arbitrary 3D cursor position (after clicking interactive, on creation it's ok to let it at cursor position).

**Comment by s-leger** [comment]
Height does start from pivot, according the way arch people do measure the height.
Blender default behaviour is to create objects right on cursor point.
I'm thinking about a "3ds max" way for create tools, to create object right under the mouse, constraint to xy plane.

**Comment by mirlip** [comment]
I think it's ok if real height (equal pivot height plus the distance chosen with the manipulator) is wrong at creation time, rotation is also wrong. My point was more set the pivot/origin at the reference height when clicking interactive to have a usable height value displayed in the manipulator. At the moment, if your 3D cursor was at 0.1 on z at creation time and you set your windows at 1m with manipulator, it will be at 1.1m in fact.
If you go the route to make it all at window creation time (take nearest wall segment to cursor position), then it would be awesome to make everything at once. Add the boolean and make the rotation like interactive mode, and lock the origin's height to the wall's origin's height.

**Comment by mirlip** [comment]
with a "follow path" parenting type to a curve followinf the wall shape, it could also be possible to constraint the window position to the whole wall and make it slide on it, following the angles.

**Comment by s-leger** [comment]
Smart create tool and follow path definitely are pretty good ideas - and probably the way to go.
Must take care to prevent deps cycle with boolean, But look like wall manipulators updating a curve may prevent this (as long as curve depends on reference point).
Seem closer to ifcOpenshell data model too.
Setting altitudes at boolean time is not an option as we must be able to make more than 1 level at time.

**Comment by s-leger** [comment]
Curve constraint dosent work as expected for this, as objects location change when length change, and the biggest issue is with orientation looking like interpolation between first and last segment -not certain about this, but look something like that-.

So after initial tests feel like i must improve childs manipulators so they are able to handle a window crossing an edge to follow next or last one, and trigger update of all manipulators.
This may also be needed to support wall from curve when curve is realy curve and we end up in having many wall segments.

Also using a curve constraint will lock your windows and prevent copy between levels.
Other negative point is the curve itself, as it is one more object to handle.
I do try to avoid multiple objects when not necessary/logical in a user point of view as user may delete it, unparent and so on.

**Comment by mirlip** [comment]
yep, indeed the follow path constraint was a bad idea. 
Locking the Z position should indeed be enough for windows. Then maybe a manipulator to choose to which level the window belong in a building would help to automatically adjust height and move the boolean from one level to the other.

**Comment by s-leger** [comment]
Won't constraint windows to wall's bottom, avoiding artificial limitation where not necessary.

* A single wall may cover more than 1 level.
* A window may be between two levels.

In visualisation from 2d workflow, you'll typically create each level on the xy plane, add openings and then move your "reference point" helper to the final 3d location.
Reference point does handle fast moving from 2d to 3d location within single click.

So may constraint window creation on xy plane.

**Comment by s-leger** [comment]
Draw windows and doors over a wall fix this issue at create time by adjusting object location according bottom of the wall.
