### ISSUE TITLE
Render thumbs not in Tool menu in 2.8/documentation is out of date

### ISSUE THREAD

**Issue by watercolorhearts** [s-leger/archipack#120]
Archipack version: 2,0,9

Blender version: version: 2.80 (sub 68), branch: blender2.7, commit date: 2019-05-17 00:03, hash: 2a9214eaaf04, type: Release
build date: 16/05/2019, 18:10

Os version: Windows 7 64-bit

Description of the issue: Following the final steps in this page, I am not able to locate the render thumbs button anywhere. [guide to thumbs on Wiki](https://blenderzen.com/2018/01/30/discover-the-archipack-add-on-in-blender) Pushing T just opens this menu: [image](https://i.imgur.com/EkImUqB.png)

**Comment by s-leger** [comment]
2.0.x series ship with thumbs, so, no need to render. 
relevant documentation is available [here]( https://blender-archipack.gitlab.io/)
