### ISSUE TITLE
Creating floors: sometimes normals are flipped

### ISSUE THREAD

**Issue by aldanor** [s-leger/archipack#126]
Here I'm using the outer wall to create floors, it created two separate floor meshes on both sides of the arch (for some reason), but one of them has wrong normals as it's flipped in the wrong direction:

![image](https://user-images.githubusercontent.com/2418513/60539002-a75f1580-9d03-11e9-8b07-b2a55b29ce64.png)

**Comment by aldanor** [comment]
Just a few other weird ones (not floors) related, but I guess these are caused by the boolean modifier?

![image](https://user-images.githubusercontent.com/2418513/60539142-e7be9380-9d03-11e9-9a98-83bf5db1fc58.png)

![image](https://user-images.githubusercontent.com/2418513/60539153-ef7e3800-9d03-11e9-8c17-f19df8508950.png)

**Comment by aldanor** [comment]
Also, what's the easiest way to merge those two floor faces into one?

(Otherwise texturing will be all messed up because there will be a seam; if just join them, one of them is facing the wrong direction again)

**Comment by s-leger** [comment]
Hi,
Assuming you are using "real-time" preset, select both and use CTRL + J to join both mesh into one.
Do not change any archipack parameter on resulting mesh (select and use "kill archipack" in tools tab) as this will regenerate a new mesh.

There is nearly no way to handle wrong face orientation after boolean while keeping the whole stack interactive, but looks like something is going wrong in blender's side.

Last one is the door soil, already reported as flipped.
