### ISSUE TITLE
No properties in view tab

### ISSUE THREAD

**Issue by vidicba** [s-leger/archipack#127]
Archipack version:
1.2.83
Blender version:
2.8
Os version:
Windows 10 
Description of the issue:
Hi, I wanted to use the archipack but I couldn't find the room button. I did some research and found out that I am missing a tab in the view tab.

**Comment by s-leger** [comment]
Hi you probably looking at an archimesh feature.
Archipack provide walls but no "room" entity.
Parameters are in the right tab of 3d view, shortcut "N"

**Comment by vidicba** [comment]
> Hi you probably looking at an archimesh feature.
> Archipack provide walls but no "room" entity.
> Parameters are in the right tab of 3d view, shortcut "N"

Thanks! I didn't know you removed the room feature.
