### ISSUE TITLE
undo not working correctly

### ISSUE THREAD

**Issue by lucasdotson** [s-leger/archipack#128]
Archipack version:
1.2.83
Blender version:
1.8
Os version:
windows 10
Description of the issue:
when you undo with this add on, all of the measurements for the assets disappear not allowing you to change them anymore.  this includes meshes you don't have selected.

**Comment by s-leger** [comment]
In order to enable / disable manipulate mode for selected object, open the right panel of 3d view, archipack tab, and click on "Manupulate".
Undo disable manipulate mode as object's data are changing and if python keep a reference to destroyed data blender will crash.
