### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by advancingu** [s-leger/archipack#129]
Archipack version: 2.0.9

Blender version: 2.80rc1

Os version: Ubuntu

Description of the issue:
* Changelogs of releases 2.0.5, 2.0.6, 2.0.7, 2.0.8, 2.0.9 are missing on [https://blender-archipack.gitlab.io/whats new.html](https://blender-archipack.gitlab.io/whats%20new.html)
* No documentation exists on how to use `Sunlight`, for example it is completely unclear what kind of animation is produced by `Shadow study`.

**Comment by s-leger** [comment]
Hi,
Sunlight "shadow study" use both extreme ephemeris (you may create ephemeris curves to materialize the path in use), you must set the light to "Sun" and use cycles to get precise results.

Also animate still is not documented, and not that much straightforward.

Will probably make a video tutorial for skylight usage soon, but feature still not frozen for it so was waiting a bit. 

Written documentation was left behind for same reasons, things like terrain, beam and sun are pretty recent additions, so will rely on video tutorials.

I'm not a shadow study expert, feel free to ask for features you want to make it usefull for typical usage.
