### ISSUE TITLE
no presets appearing.

### ISSUE THREAD

**Issue by netcore10** [s-leger/archipack#132]
Archipack version:1.2.83

Blender version: blender 2.80 rc 1

Os version: Windows 10 1903

Description of the issue: When I try to add a preset, it's just blank? 
![archipack blank presets](https://user-images.githubusercontent.com/181536/61254567-d8583500-a75c-11e9-9414-5794d56cbc52.png)

**Comment by s-leger** [comment]
Use "Render preset thumbs" in file -> user preferences -> Add-ons -> archipack -> Setup actions

**Comment by netcore10** [comment]
thanks
