### ISSUE TITLE
Preset thumbs rendering but never saved.

### ISSUE THREAD

**Issue by Olisil** [s-leger/archipack#138]
Archipack version: 
1.2.83

Blender version: 
2.8

Os version: 
Win10

Description of the issue:
When trying to create any object there's a black empty preset window. When finally finding out about the need to render presets in preferences I hit that button and the render process starts in the command window. When that is finished, nothing changes. It's all the same, except the confirmation dialog to render is closed. There still are no presets when creating objects. What to do?

**Comment by s-leger** [comment]
Hi could you tell me more about the version of your blender 2.8 ?  
is it the release, older one ?

**Comment by Olisil** [comment]
Hi,
Seems like a restart of Blender solved it. This was 2.8 E-Cycles version, but both ordinary 2.8 and the E-Cycles version worked fine after restart.

**Comment by s-leger** [comment]
Thank you for your reply,
Using E-cycles myself here, but not checked on it. There where changes done in lights and image close to release, so versions older than release are likely to fail to render.
