### ISSUE TITLE
Error when creating floors in curved walls

### ISSUE THREAD

**Issue by AyelGoth** [s-leger/archipack#141]
Archipack version: 2.1

Blender version: 2.8 Snap

Os version: Linux Kubuntu 19.04

Description of the issue: I have created several curved walls, when I try to create floors automatically from all the walls, some floors are not created correctly in rooms with curved walls. This same error happens when I try to create slabs from the same curved walls.

This can happen because of a calculation error in Boolean operations.

I attach blender file with the walls that I try to create the floors.
[Central UAMI Final.zip](https://github.com/s-leger/archipack/files/3597700/Central.UAMI.Final.zip)

**Comment by s-leger** [comment]
There is an obvious bug in the wall's boundary generation, this is weird as walls should fails the same way as curve. 
You may generate a "Slab" curve to see what happen - under Create objects in tool tabs of walls parameters.

By the way, you should update to 2.2.1 using 
https://blender-archipack.org/archipack-update.php

In the meantime, and once 2.2.1 setup, use a section object (Create->Add 2d objects) to generate a floorplan from your walls (over the windows so you only get walls footprints) and then using the "2d to 3d" workflow, select polygons and generate curves for both floors and slab.
Take a look at :
https://youtu.be/AeVD2UxSx4g?t=378
for the section, and 
https://youtu.be/lBvBIfJAVB0
for 2d to 3d workflow

**Comment by AyelGoth** [comment]
I tried what you told me, but when I set it to create curved lines, the same mistake happens. Curves created in 2D are wrong.

**Comment by s-leger** [comment]
Yes, "slab curve" is wrong and this is the source of your issue. But at least we are able to narrow down the issue.
You must rely on 2d to 3d workflow then.

**Comment by AyelGoth** [comment]
When I create walls from curves with the same wall diagram, the lines are deformed and the mathematical result differs from the initial configuration. The result of the operations gives me this.
![untitled](https://user-images.githubusercontent.com/5136303/64654599-19d52b80-d400-11e9-9af8-696e4f556f5d.png)

**Comment by s-leger** [comment]
According release notes, you can see that this issue (2d to 3d workflow in general) is fixed since 2.2.0
https://blender-archipack.gitlab.io/whats%20new.html#release-2-2-0

**Comment by s-leger** [comment]
Fixed the issue, will be part of 2.2.2 release
