### ISSUE TITLE
Erroneous measures

### ISSUE THREAD

**Issue by AyelGoth** [s-leger/archipack#143]
Archipack version: 2.1

Blender version: 2.80

Os version: Kubuntu 19.04

Description of the issue:

When setting the measurements in separate decimal places. When you create a wall that measures 5 m., and you want to change the size to 4 or 6 meters, instead of the measurement appearing as 4 or 6 m., you see 3 m 100cm or 5m 100 cm.
![Screenshot_20190911_152949](https://user-images.githubusercontent.com/5136303/64724958-ea7af900-d4a9-11e9-92f8-bad8cf9c1648.jpeg)

**Comment by s-leger** [comment]
This is a precision issue, where stored value is 5.999999. Disable "separate units".
