### ISSUE TITLE
Create Level Layer

### ISSUE THREAD

**Issue by AyelGoth** [s-leger/archipack#144]
Archipack version: 2.1

Blender version: 2.80

Os version: Linux Kubuntu 19.04

Description of the issue: Archipack may have the option to create display layers when a user creates a new level of the building. Objects created at that level would be added to that level's display layer.

I give an example of a blender file of how I have organized the levels and layers of visualization. It's comfortable to work with, because if I need to modify something at that level, I load the visualization layer so that you only see the objects I have to work with at that level.

[Central UAMI Planos.zip](https://github.com/s-leger/archipack/files/3602600/Central.UAMI.Planos.zip)

**Comment by s-leger** [comment]
Will not enforce any artificial structure constraints other than what's required for the addon to work, so anyone is free to use either collections / view layers / whatever structure fits the needs.
At some point you also are able to use collections to control "by level" visibility, this is what collections are about, with the advantage of allowing collection instances.
