### ISSUE TITLE
Error when constructing interior walls

### ISSUE THREAD

**Issue by AyelGoth** [s-leger/archipack#145]
Archipack version: 2.1

Blender version: 2.8

Os version: Linux Kubuntu 19.04

Description of the issue: When one has built walls, floors, slabs and ceilings, and then merge 2 or 3 references. After trying to build more internal walls or windows; the floors, slabs, etc. are deformed.
[Central UAMI Final.zip](https://github.com/s-leger/archipack/files/3629120/Central.UAMI.Final.zip)

**Comment by s-leger** [comment]
Hi,

I don't want to provide any support for non customers of 2.x version of archiapck.

Best regards,
Stephen.
