### ISSUE TITLE
Mettre un element de type fenetre

### ISSUE THREAD

**Issue by micker** [s-leger/archipack#146]
Archipack version: 1.2.8

Blender version: 2.8

Os version: win10

Description of the issue: 
bonjour je découvre votre addon celui intégrer a blender de base ... et j'ai beau fermer ma piece quand j'ajoute une fenetre cela ne fait jamais l'operation boleene pour troué le mur
je suis sur que c'est ma faute ... mais je ne comprend pas comment cela fonctionne
Merci par avance

**Comment by s-leger** [comment]
Bonjour,
Il y a deux manières d'ajouter des fenêtres,

- en utilisant l'outil "dessin" (le petit crayon), il devrait faire le prececment directement.
- si vous créez la fenêtre sans utiliser cet outil, sélectionnez votre mur, et dans l'onglet outils, il y a le bouton "auto-booléen" qui se chargera des percements.

**Comment by micker** [comment]
ok je vais essayer merci !!!
