### ISSUE TITLE
Archipack and Filmic Blender not working at same time

### ISSUE THREAD

**Issue by adrivikt** [s-leger/archipack#147]
Archipack version: 1.2.83

Blender version: 2.80

Os version:

Description of the issue:

 I installed the Filmic Blender to use instead of the sRGB for the color management! Since then Archipack is not working anymore and i get an error. 
When I change back to the original color management file, everything works fine again. 
Does someone had the same issues before? I would like to keep using both components... 
Thank you so much in advance for any advice!!
![error](https://user-images.githubusercontent.com/56279077/66352612-3e211b00-e960-11e9-9b50-11195b16ba65.JPG)

**Comment by s-leger** [comment]
Hi, 
This is a known issue, here you'll find a solution.
https://github.com/s-leger/archipack/issues/137#issuecomment-524552613
