### ISSUE TITLE
New Wall Direction

### ISSUE THREAD

**Issue by jobdiogenes** [s-leger/archipack#148]
Archipack version:
2.09 Pro
Blender version: 
2.8
Os version:
Linux Mint 19.2

Description of the issue:
New Wall Direction goes Straight whatever config is in ArchiPack preferences.

### Solutions

**Basic Fix** - Make preferences work

**Good Fix** - Change UI Behavior
- Change Archipack Wall Direction Setting to Degrees 
- Make last change in draw interface by left-click and type in degree, to be the current default
- Left-click+Shift in new wall arrow, reverse (degree * -1) current default
- Left-click+Ctrl in new wall arrow, reset to interface default

Thats all.

Thanks to this great plugin.

**Comment by s-leger** [comment]
You should use draw tool to create walls, it is faster my magnitudes and way more easy. 

New wall segment direction is always straight, there is nothing in preferences for that.
Wall draw method in preferences is intended to make wall's outside on the right side of base line when drawing (clockwise or counterclockwise)

2.0.9 is outdated, you should update to 2.2.2

**Comment by jobdiogenes** [comment]
After some tests, I found what was happening. 
The 90º behavior are in archipack free. 

In any way, would be nice to add UI improvements to draw wall
- Next Wall Draw segment repeat last degree used 
- Ctrl-Left-click goes 90° 
- Shift-Left-click goes -90º
