### ISSUE TITLE
Report: Error with Filmic addon

### ISSUE THREAD

**Issue by jsalsburg** [s-leger/archipack#152]
Archipack version: 2.0.9

Blender version: 2.8

Os version: Windows 10 64bit

Description of the issue: Truss, Beam, and Sunlight create objects, nothing else without errors. There is no obvious way to copy/paste the error messages so I made a screenshot.
![image](https://user-images.githubusercontent.com/4895859/68034366-c1434180-fc7e-11e9-8181-095e976bb99e.png)

**Comment by s-leger** [comment]
This is a know issue fixed in 2.2.2 with non regular filmic addon.
Will provide an update download link by e-mail.

**Comment by jsalsburg** [comment]
Thank you! I am anxious to get started.

**Comment by jsalsburg** [comment]
I received the link for the version that solves this problem, apparently there is an issue with the Filmic Addon, causing this problem. I just installed the new version 2.2.2, will build a model and put Archipack PRO through its paces. I thank everyone for their prompt response.

**Comment by Walterthecat** [comment]
> This is a know issue fixed in 2.2.2 with non regular filmic addon.
> Will provide an update download link by e-mail.

I tried adding the colorspace Raw section of the original color management code to the filmic code as suggested and it worked but is version 2.2.2 a more stable version? Sorry, this is my first time coding.

**Comment by s-leger** [comment]
2.x is the pro version of archipack, development and bug fix occurs in a daily basis so yes it is by far more stable and feature rich than 1.2.x version. 
This issue also was fixed in 1.2.x version, but we still are waiting for a new blender release.
