### ISSUE TITLE
render presets thumbs issue.

### ISSUE THREAD

**Issue by ptiloupanda** [s-leger/archipack#153]
Archipack version:1.2.83

Blender version:2.8

Os version:Ubuntu 19.10

Description of the issue:
Just pressing render presets thumbs. As it was not working. 
I try to execute manually the __init__.py, and it says that I have a import relative path issue which is absolutely the case : Python 3 does not allow this "behavior" anymore (eg from . import archipack_door). I'm a python medium developer so I know quiet well the issue but I want a proper answer to this question. Please HELP me :=))

**Comment by s-leger** [comment]
Render preset thumbs is working here as expected.
Once done, restart blender as thumbs are not reloaded dynamically. 
By executing the init.py by hand you are breaking the "module" context, where relative import using . does make sense.

**Comment by ptiloupanda** [comment]
Big thanks for your time. I really appreciate. Do you have a kind of logs which could help me to debug why I'm still in error ?

**Comment by s-leger** [comment]
Background rendering should log progress / errors right into the console. So start blender using a console and then keep a look at it while rendering.
Did you setup the default material library ?

**Comment by Rudolfjvr** [comment]
> Big thanks for your time. I really appreciate. Do you have a kind of logs which could help me to debug why I'm still in error ?

Did you manage to find the issues as I have the same problem?
