### ISSUE TITLE
Click and draw a wall (from your YT-Tutorial)

### ISSUE THREAD

**Issue by virtualdreams** [s-leger/archipack#154]
Archipack version: 2.2.2

Blender version: 2.80

Os version: Windows 10

Description of the issue:

You mention in your tutorial video https://www.youtube.com/watch?v=JV3S84oDN0Y to draw a wall with a simple click and drag. But this don't work. It draws only the selection box. The shortcut "c" to close a wall don't work and so on.

The blue box only appears only if i click on a arrow or square.

**Comment by s-leger** [comment]
The exact steps for wall creation are:
Press “Wall” button, release the mouse button and move pointer at desired wall start location. you may use snap so locate your start point in a precise way.
Press left mouse, to create start point, keep left pressed and drag to end point. Once at end location, release. Again snap does work here too.
Then either

move mouse pointer anywhere beside small square handle (not too close), press left to create next segment, (optionnal 2*y key for perpendicular local constrain) keep left pressed and drag to endpoint, then release.

press enter to create next segment, drag cursor without pressing to endpoint, (optionnal 2*y key for perpendicular local constrain), press left to confirm.

Close your wall by pressing c (wich create last segment between current and first one).

This does work in Left click select mode, any right click will exit from the draw tool.

**Comment by virtualdreams** [comment]
Ok, this work as long i don't leave the wall mode (deselect). If i select the wall again, this don' t work anymore. The bluebox also don't appear.

**Comment by s-leger** [comment]
Yes, 
restarting "draw tool" is a on the todo list.

**Comment by virtualdreams** [comment]
Alright, thanks for this information.

**Comment by s-leger** [comment]
Restarting "draw tool" for wall is available on 2.2.3 version. 
Select the wall, hold ALT and click on "Wall" button in Create tab of 3d view right panel.

**Comment by virtualdreams** [comment]
It works now. Thanks for the fix. 👍
