### ISSUE TITLE
Archipack not working properly 

### ISSUE THREAD

**Issue by loverofmonika** [s-leger/archipack#155]
Archipack version: 1.2.83

Blender version: 2.80

Os version: i core 5

Description of the issue: When using the archipack, i am only getting this and this is the same for all choice based mesh like stairs, roof etc
![image](https://user-images.githubusercontent.com/39667583/69013550-f9e35a80-09a2-11ea-8997-b750057d978a.png)
This is also the same result on a different PC. 
Is this a bug and is there any way to fix this problem?

**Comment by s-leger** [comment]
Blender's official archipack addon require additional setup steps in order to work.
Preferences -> add-ons -> archipack -> "Setup actions" -> press "render thumbs"
