### ISSUE TITLE
Not showing object 

### ISSUE THREAD

**Issue by dikisp** [s-leger/archipack#156]
Archipack version:

Blender version:

Os version:

Description of the issue:

**Comment by s-leger** [comment]
Without any information i'm not able to provide any help.

**Comment by dikisp** [comment]
oh tahaks ,
resolved

**Comment by dikisp** [comment]
hallo,
i want lern about add ons for blender 
what should i do ?

**Comment by s-leger** [comment]
Learning from built-in addons by looking at code could be a good starting point. 
Try small changes.
