### ISSUE TITLE
Add Menu doesn't display all of the Archipack Objects

### ISSUE THREAD

**Issue by richardebel** [s-leger/archipack#157]
Archipack version: 2.2.3

Blender version: 2.80

Os version: MS Windows 10 Pro

Description of the issue:
Add->Mesh->Archipack: only displays 4 items: Wall, Draw, Window, Door

**Comment by s-leger** [comment]
There is a bug in the add menu, will fix in next release.
In the meantime use the "Create panel" in right of 3d view.

**Comment by s-leger** [comment]
Fixed in 2.2.4
