### ISSUE TITLE
Nothing shows up.

### ISSUE THREAD

**Issue by romanayub111** [s-leger/archipack#159]
Archipack version:1.2.83

Blender version:2.81

Os version:Windows 10 Pro

Description of the issue: The walls work okay as they should do but If I click on anything other than the wall then a black pop up appears with a search bar( I guess its a search bar) on top. Its totally black and has nothing in it. I just can do anything after it. I can't even close it then.

![Untitled](https://user-images.githubusercontent.com/59225979/71445117-c1b8ff80-2738-11ea-966b-21b1d199e3cc.png)

**Comment by s-leger** [comment]
https://s-leger.github.io/archipack/setup.html#activate-the-add-on
