### ISSUE TITLE
Roof grand-child not showing correct altitude

### ISSUE THREAD

**Issue by koob3d** [s-leger/archipack#162]
Archipack version:
1.2.83
Blender version:
2.81
Os version:
windows 10
Description of the issue:
I have a roof with a child roof with x and y distance.
The child roof also has a child with x and y distance.
![grandchildZoffset](https://user-images.githubusercontent.com/25620257/73591041-a385b280-44e1-11ea-8cf8-686dfdeec990.png)
I think what is happening is that the grand-child roof has the z value of the grand-parent instead of the parent.
When I correct the height it is undone on the next update.
I played with the parent index but did not score anything useful. Not sure how to find the parent index either.

**Comment by s-leger** [comment]
Hmm i see, this is a limitation, fixed, will push for next blender release.

In the meantime, you may use a "displace" modifier on child roof, using "Z" as direction and compensate the altitude with "Strength" value of the displace modifier.

When you press "manipulate" you'll see small numbers on roof axis, those numbers are parent index (segment index).

**Comment by koob3d** [comment]
Wow, that was quick! 
Where can I find the relevant push, when its available?
Meanwhile, the displace modifier does the job.

Many thanks.

**Comment by s-leger** [comment]
Pushed today on master branch, should be available on next build bot version / next release, depends on blender fundation.
https://developer.blender.org/rBA8443147d3e96

Also fixed on archipack PRO, will be in next release.

**Comment by koob3d** [comment]
I nabbed the new file for my 2.82 installation (windows wont let me change the system install of 2.81), works a treat.
Thanks again.
