### ISSUE TITLE
Error when activating 2.2.4 "Cannot import name 'CutHandle'... "

### ISSUE THREAD

**Issue by fodevaux** [s-leger/archipack#163]
Archipack version: archipack_2.2.4

Blender version: 2.8.1

Os version: Mint 19

Description of the issue:

Error when activation. "Cannot import name 'CutHandle'... "
See screenshot. 
(No issue with archipack 2.0.9 though)

![Capture d’écran_2020-02-01_13-11-03](https://user-images.githubusercontent.com/10889235/73591884-7c84ac00-44f4-11ea-94a7-7694c6428919.png)

**Comment by s-leger** [comment]
In addon preferences, disable old version expand archipack tab and click "Remove", restart blender, then setup 2.2.4.

**Comment by fodevaux** [comment]
Great. The "restart blender" part was missing. Seems obvious now. Thanks a lot !
