### ISSUE TITLE
Keyframes on mesh parameters?

### ISSUE THREAD

**Issue by thely** [s-leger/archipack#164]
Archipack version: 2.2.4

Blender version: 2.81a

Os version: OSX 10.13.6

Description of the issue: I'd like to be able to animate some of the parametric objects in Archipack, but it doesn't seem to work. I'm trying to animate just the width of a window mesh, using the width parameter in the N menu. If I use keyframes to try to animate a window growing wider and press play, the value will update, but the meshes won't. I tried exporting as an animation as well, but I just get a static object.

I've seen the possibility of animation mentioned [last year](https://github.com/s-leger/archipack/issues/129) and [the year before](https://blenderartists.org/t/archipack-1-3-8-18-04-2018/685807/498), but I don't know where 2018's supposed animation handlers are now. Is animating archipack models possible without converting the model into a normal mesh and using shape keys?

**Comment by s-leger** [comment]
Hi,
The point with animation handlers lie in render farm compatibility, this is the main reason for me to remove this ability.
It is not that hard to handle, will take a look at revert.
Keep in mind that some parameters will not be animatable even with handlers.
