### ISSUE TITLE
Give différences between 2.x version and the provided 1.2 version in Blender

### ISSUE THREAD

**Issue by metal3d** [s-leger/archipack#165]
Hello,

As 1.2.83 version is provided with Blender since a long time, I wonder what's the difference with the 2.x version that you sell.

The webpage doesn't give any precision.

Maybe you can:

- provide information on your selling page
- tell us more inside the README file

Thanks.

**Comment by s-leger** [comment]
Hi,

Find "Feature matrix comparaison" here:
https://blender-archipack.org/features/#c237

and changes log for 2.x releases:
https://blender-archipack.gitlab.io/whats%20new.html

**Comment by metal3d** [comment]
Right, didn't seen that page, sorry for that. I finally bought 2.x version (I prefer donation on opensource software but... ) ;)

I have got some stack trace in certain operation but I will open new issues for that.

I can close that issue. Thanks for you answer.

**Comment by s-leger** [comment]
Take a look at your e-mails (spam ?), you should get update instructions to download latest release.
