### ISSUE TITLE
Archipack beam is not diplayed (visible)

### ISSUE THREAD

**Issue by anttusun** [s-leger/archipack#167]
Archipack version:
2.2.6
Blender version:
2.81.16
Os version:
Win 10 ... 64bit v.
Description of the issue:
After upgrading to Archipack 2.2.6 I cant create beam ... ist is not visible, all I can see is one dot. The properties panel displays default dimensions and all, but the beam is not visible. It is also created as object in the Scene Collection. I tried to change material but no effect.

**Comment by s-leger** [comment]
Confirmed in 2.2.5 - 2.2.6, 
will fix for next release.
in the meantime you may alter line 165 of archipack_beam
change 
color = self.random_color()
into
color = self.random_color

**Comment by anttusun** [comment]
Thanks, all OK now.
