### ISSUE TITLE
No sidebar menu for archipack

### ISSUE THREAD

**Issue by TeejSingh** [s-leger/archipack#168]
Archipack version:1.2.83

Blender version:2.80

Os version: Windows 10 Pro

Description of the issue:

There's no side bar menu when loading the Archipak addon, this kills the flow of work as I'm unable to access the boolean function from the gui menu. As you can see in the screen grab that the screen left side bar menu is empty and I have no idea on how to get this working.

Any insights shared would be appreciated. 

Thanks, 

Teej

![blender_archipak](https://user-images.githubusercontent.com/62219370/76710176-30d13f00-66fd-11ea-831d-5abaf43cb828.jpg)

**Comment by s-leger** [comment]
Hit "n" key to display the right side bar in 3d view.
