### ISSUE TITLE
I Cant Activate the Archipack 1.3.8 in Blender 2.82

### ISSUE THREAD

**Issue by ikarokavalcante** [s-leger/archipack#169]
Archipack version: 1.3.8

Blender version: 2.82

Os version: Windows 10* 64-bit

Description of the issue: The archipack that is in blender dont have assets library and I dont know why, so I search for an updated version, and I installed properly but it doesnt work, could someone help me?

![error](https://user-images.githubusercontent.com/61336583/76821379-8afcfd80-67ec-11ea-9b83-b365dd623d3d.png)
![Version](https://user-images.githubusercontent.com/61336583/76821380-8b959400-67ec-11ea-83a3-6532739a0852.png)

**Comment by s-leger** [comment]
Version 1.3.8 is designed to work under blender 2.79 only.

Setup instructions for 1.2.8x in blender 2.8+
https://github.com/s-leger/archipack/wiki/Setup#archipack-135--archipack-official-1281-for-blender-28
