### ISSUE TITLE
Section tool: context object has no attribute

### ISSUE THREAD

**Issue by Stavson** [s-leger/archipack#170]
Archipack version:2.0.9

Blender version:2.82/2.83

Os version: Windows 10

Description of the issue: When updating a new section I get a traceback error saying 'context' object has no attribute 'depsgraph' when it gets to line 61. 
![section error](https://user-images.githubusercontent.com/47071876/79259471-9ff79b80-7e41-11ea-93ce-7c3ae6586218.PNG)

I've tried a couple versions of archipack as well as as multiple versions of Blender.

Thanks in advance for looking into this!

**Comment by s-leger** [comment]
Hi 2.0.9 version is outdated, you should find download link for latest version in e-mail from blender-archipack.org

**Comment by Stavson** [comment]
Wow. I can't believe I was still using such an old version! Thanks!
