### ISSUE TITLE
i can't select the archipack in my blender 2.8

### ISSUE THREAD

**Issue by aknpresents** [s-leger/archipack#171]
Archipack version: 1.2.83

Blender version: 2.8

Os version: 8.1 pro

Description of the issue: i have traceback problem with selecting the archipack on blender

**Comment by s-leger** [comment]
Hi,
update to latest blender 2.82a / 2.83
Always disable manipulators with right click / esc when you are done with object manipulation.

**Comment by Beatriz229** [comment]
Hi,
I'm having the same problem, but I'm using Blender 2.83. There's a note "Upgrade to 2.8x required". Should I try other Archipack version?
Thanks!

**Comment by s-leger** [comment]
Version in this repository (1.3x / 1.40_dev) are only compatible with blender 2.79
Blender 2.8+ series ship with archipack 1.2.8x so you only have to enable in add-on preferences.
