### ISSUE TITLE
Archipack 1.3.8 on Blender 2.82a Error

### ISSUE THREAD

**Issue by baldyman01** [s-leger/archipack#172]
Archipack version:1.3.8

Blender version: 2.82a

Os version: Ubuntu 19.10

Description of the issue: 
![Screenshot from 2020-04-28 23-30-06](https://user-images.githubusercontent.com/33987743/80544176-6037c480-89a8-11ea-8538-654f574ed535.png)

**Comment by s-leger** [comment]
Archipack 1.3.8 is for Blender 2.78 / 2.79
take a look at [official website for more informations](http://blender-archipack.org/)

**Comment by baldyman01** [comment]
OK. Is there a version that is supported on 2.8 that doesn't crash all the time?

**Comment by s-leger** [comment]
[archipack pro 2.x](https://gum.co/ZRMyP)

There is a known issue with native 1.2.8x version, you should disable manipulators on objects when done using right mouse click, so many objects are not left in "manipulate" mode.
Pushed a fix, but have to wait next blender release.
