### ISSUE TITLE
Length shown on hints aren't consistent with value given to walls on input

### ISSUE THREAD

**Issue by alivcor** [s-leger/archipack#176]
Archipack version:1.2.83

Blender version:2.82

Os version: Mac OS 10.13.5

Description of the issue:

The lengths of walls shown as hints are not consistent with actual measurement specified.

The hint for Wall 7 shows "1.77", it is neither consistent with the value I specified ("-5.88") in the input box for Wall 7, nor with the actual measurement using measure tool. If it is a problem with units, it should match at least with the value which we specify in the input box, which isn't the case either.

![image](https://user-images.githubusercontent.com/12253342/83314065-ae79f680-a1e6-11ea-88f0-a17e21fe6f4b.png)

**Comment by s-leger** [comment]
The room entity belongs to archimesh add-on. Not related to archipack.

**Comment by alivcor** [comment]
Thanks - for anyone bumping into this issue - the hints show the distance in "blender grid units" - one box = 1 unit. The scale factor on the right panel determines how 1 unit maps to the metric system you have chosen, so you need to adjust the scale factor for the measure tool measurements to match with the actual measurements.
