### ISSUE TITLE
Boolean operations on Drafts/Feature Request

### ISSUE THREAD

**Issue by RyanJMcGowan** [s-leger/archipack#181]
Archipack version: 2.3.0

Blender version: 2.9

Os version: Win 10 Pro

Description of the issue:

Request to take in boolean operations on Roof Drafts to act on Roof generation without having to permanently apply the boolean operation to the geometry. Without applying, the boolean operations are ignored. Applying the boolean works great, but making one change means having to go through and re-add all boolean operations again.

Note that boolean operations on the final Roofs themselves is a workaround as well, but comes at a performance cost when generating a lot of tiles and beams, and also doesn't generate the edge beams and fascia boards dynamically. Roof Holes is also a workaround, but has topology issues with the Roman Roof tiles.

**Comment by s-leger** [comment]
Use roof "Cutter" instead.
https://youtu.be/0wNgjWvDKBY?t=528
In 2.3.0 there is a know issue with roof's cutter initialization,select the "cutter" go in the Axis tab, and increase segments to 5 then decrease to 4.

Most topology isses you may encounter with Roman tiles comes from "bevel" value, try to lower a bit.
