### ISSUE TITLE
slab cutter cuts through the floor on the ground below

### ISSUE THREAD

**Issue by lg9cgi** [s-leger/archipack#182]
Archipack version: 2.3.0

Blender version: 2.82

Os version: Windows 10

Description of the issue:

the slab cutter cuts through the floor on the ground below.

![Unbenannt](https://user-images.githubusercontent.com/20164728/85946646-13d81900-b946-11ea-8595-40572ee67dc9.PNG)

**Comment by s-leger** [comment]
Slab cutter rely on reference point children to find wich floor must be cut.
The floor below probably is child of the same reference point than the slab itself.

**Comment by lg9cgi** [comment]
thanks, that solved my problem! btw great add-on 👍
