### ISSUE TITLE
Stairs through floor no hole

### ISSUE THREAD

**Issue by Timlazisa** [s-leger/archipack#183]
Archipack version:2.0

Blender version:2.8

Os version:Win 10 64bit

Description of the issue:So I designed my first house slowly working my way through the various functions, but for the life of me can not figure out how to cut a hole though a 1st floor with a stairs. The Stairs obviously goes through the floor but there is no hole so you can see up or down the stair through the floor. Can someone help please/
![Screenshot (116)](https://user-images.githubusercontent.com/65236573/86390648-5c6a3c00-bc90-11ea-9387-d29e7e80795d.png)

**Comment by s-leger** [comment]
Use a slab cutter to create hole over your stair.
https://youtu.be/3r8uHOw_A48?t=19

**Comment by Timlazisa** [comment]
Hi

Yeh I tried this but there's no audio and I couldn't figure out the key
strokes to move the slab cutter to the appropriate piece of floor to cut
the floor. Can you help?

Tim

**Comment by s-leger** [comment]
No keystrokes at all, only select square manipulators like you will do with a regular box select, then click on any square and move the cutter.

**Comment by Timlazisa** [comment]
Ok Thanks Steven

Thats pretty cool. How do I take care of the wall as well, I have stairs
coming out of a cellar attached and example

Tim

**Comment by s-leger** [comment]
Use a mesh and set it as "custom hole" in tools tab

**Comment by Timlazisa** [comment]
I don't know what that means?

**Comment by s-leger** [comment]
https://github.com/s-leger/archipack/wiki/Custom-holes-and-walls

**Comment by Timlazisa** [comment]
Is this in the paid version because I see no item titled 'custom hole'?

**Comment by s-leger** [comment]
Yes you are right, this feature is available in 1.3.8 version for blender 2.79 and in pro version only.
But you still are able to add a hole, if the wall already has openings, select the wall and find boolean modifier "object" name - "autoboolean.xxx", select that Autoboolean object for that wall, add a boolean modifier in "union" mode and pick the hole as object.
If the wall doesn't have boolean modifier, add one in "substract" mode and pick your hole mesh.

**Comment by Timlazisa** [comment]
Awesome thanks Steven,
C'est fantastique

**Comment by Timlazisa** [comment]
Hi ya

How do I turn off ALL measurements, its getting really cluttered now and I
can't figure out how to delete them all?

Thanks

Tim
