### ISSUE TITLE
Rendering of Archipack Elements

### ISSUE THREAD

**Issue by MaineBlender** [s-leger/archipack#185]
Archipack version: 1.2.83

Blender version: 2.8

Os version: 10.13.6

Description of the issue:
Hello! None of the archipack preset thumbs are rendering (they're all white) and even when I place an element (like the floor materials from archipack), they're all white...  Is there a setting I'm missing?  You can see in the attached screenshots, when I go to add an element, none of them are rendered and then when I place an element (like the floor seen in the second screenshot, none of those are rendered either).  I did go into the "Add-ons" under preferences in Blender and hit the "render presents thumbs" but that didn't change anything...  Thank you!

<img width="2108" alt="Screen Shot 2020-07-12 at 3 32 24 PM" src="https://user-images.githubusercontent.com/67874232/87255185-8244cd00-c456-11ea-947b-f9efc2b0fde6.png">

**Comment by MaineBlender** [comment]
Here's the second screenshot... 
<img width="1500" alt="Screen Shot 2020-07-12 at 3 32 59 PM" src="https://user-images.githubusercontent.com/67874232/87255245-fed7ab80-c456-11ea-9c05-59869f957079.png">

**Comment by s-leger** [comment]
You have to setup default material library before rendering presets.
https://github.com/s-leger/archipack/wiki/Setup#download-and-setup-default-material-library
