### ISSUE TITLE
Render Presets Thumbs

### ISSUE THREAD

**Issue by Lohrrany** [s-leger/archipack#186]
Archipack version: 1.2.83

Blender version: 2.83.2

Os version: ?

Description of the issue:
![arckpack](https://user-images.githubusercontent.com/68287513/87438143-8e02d180-c5c5-11ea-8c1b-101b813d570c.png)
It is taking too long when I activate Render Presets Thumbs.

**Comment by Lohrrany** [comment]
This is Arckpack*

**Comment by Lohrrany** [comment]
And in the Create tab nothing appears

**Comment by s-leger** [comment]
Render preset thumbs process actually does use eevee to render every "factory" preset - about 40 pics.
This process usually takes less than 3 minutes.
Once done, restart blender.

**Comment by Lohrrany** [comment]
I already solved the problem, in fact I didn't need to wait for the black screen to exit, as soon as Blender unlocked I could enter it, just restart Blender, in this version 2.83 some things have changed, and the tab settings have been hidden, different from the tutorials yt in older blender versions. Thanks.
