### ISSUE TITLE
Dimension Tool broken on Pop_OS 20.04 - Re: 'scene' object no attribute 'StyleGenerator'

### ISSUE THREAD

**Issue by 4lex4rch** [s-leger/archipack#188]
Archipack version:2.3.1

Blender version:2.83.2 

Os version: Pop_OS 20.04 LTS (Ubuntu 20.04)

Description of the issue: Dimensions tool broken on different files and installations of Blender and ArchiPack.  Selecting wall then pressing 'dimension' button doesn't show anything.  'Orient' and 'Update' buttons give similar errors to one shown.  Seems to be an issue with "StyleGenerator".  I installed in various ways the plugin and blender to see if I could make a change with no luck.  Google was no help.  I hope you can find a solution.   Either way, I love your work.  Thanks for the first giant leap in Blender architectural BIM/Viz/draft combination.
 
![Screenshot from 2020-07-20 16-04-04](https://user-images.githubusercontent.com/68603823/88074183-14c72980-cb45-11ea-9566-0fb6f7c8fcd8.png)

**Comment by s-leger** [comment]
Hi Alex, 
Setup the Measureit ARCH addon will fix this issue.
[MeasureIt ARCH](https://github.com/kevancress/MeasureIt-ARCH/releases/tag/mARCHv0.4.5)

[download](https://github.com/kevancress/MeasureIt-ARCH/releases/download/mARCHv0.4.5/MeasureIt-ARCH-v0-4-5.zip)

**Comment by 4lex4rch** [comment]
Thanks! MeasureIt ARCH would not install until I installed Blender BIM, but it's all working now.  So, to anyone else with the same issues there may be a chain of plugins needed.
