### ISSUE TITLE
Manipulate walls not working / needed to be manually activated each time 

### ISSUE THREAD

**Issue by bigotes423** [s-leger/archipack#189]
Archipack version: Archipack Pro latest update made today 07 24 2020

Blender version: 2.8

Os version: Win 10

Description of the issue: when drawing a wall, if I grab a segment all measures are no longer visible and there is no way to maipulate the wall further. I have to manually press the small hand (topright corner). every time. What did I do? It was working until yesterday. 

![image](https://user-images.githubusercontent.com/68729427/88370524-7cbe7f80-cd92-11ea-88c6-49bae6585ffa.png)

**Comment by s-leger** [comment]
Ensure Gizmos are active.
![gizmos](https://user-images.githubusercontent.com/7442572/88389403-c02ae500-cdb6-11ea-926c-c9dc7bfa9b11.png)

Please report errors for version 2.x using "Create->About->Contact support"
