### ISSUE TITLE
Adding 90 degrees bent wall segments impossible 

### ISSUE THREAD

**Issue by bigotes423** [s-leger/archipack#190]
Archipack version: latest one

Blender version: 2.8 

Os version: win 10

Description of the issue:
When adding a new wall segment by clicking on the arrow it is impossible to automatically add the new piece of wall at 90 degrees, but only alligned with the previous. Is there a way to automatically add the following piece of wall inclined of 90 degrees? At the moment i must add the wall in picture 1 and subsequently bent it of 90 degrees like in pic. 2. pls help because this is very annoying.

![image](https://user-images.githubusercontent.com/68729427/88422636-d9e61f80-cdea-11ea-816b-d7624190b6c5.png)

**Comment by s-leger** [comment]
in 2.x version use draw tool instead.
see [this video](https://youtu.be/JV3S84oDN0Y) as reference
You may restart draw tool at anytime by selecting the wall and hold alt when you press "Wall" button in create panel.
