### ISSUE TITLE
Impossible to work with. 2 days struggling with drawing walls 

### ISSUE THREAD

**Issue by bigotes423** [s-leger/archipack#191]
Archipack version: latest one

Blender version: 2.8

Os version: 

Description of the issue: Impossible to work with. 2 days struggling with drawing the simplest plans just to practice. I can't even imagine in the rieal work. I have always problems, impossible to continue walls. Adding new segments impossible (also in draw mode). There are always errors, crashes from time to time. Impossible to work with. Please consider a refund. 

![image](https://user-images.githubusercontent.com/68729427/88450721-5f9cb600-ce51-11ea-81ee-fd79fbc28639.png)

**Comment by s-leger** [comment]
For archipack 2.x support request please use 
![support](https://user-images.githubusercontent.com/7442572/88451078-3d586780-ce54-11ea-8eee-e2148ccfa1f8.png)

There is a known issue with dimensions in 2.3.1, you have to download and setup [MeasureIt ARCH](https://github.com/kevancress/MeasureIt-ARCH/archive/master.zip) addon.
