### ISSUE TITLE
XY axis does not follow cursor when trying to draw wall

### ISSUE THREAD

**Issue by Moult** [s-leger/archipack#194]
Archipack version: 2.3.1

Blender version: 2.83

Os version: Gentoo Linux

Description of the issue:

Also, when I click the wall tool, an X and Y axis appears on my screen where my cursor last was... but when I move my cursor, the XY axis intersection doesn't follow my mouse. Is this a bug? See screenshot below where I've circled the XY intersection.

![image](https://user-images.githubusercontent.com/88302/89133512-c3b12f80-d55f-11ea-8048-7676190b2069.png)

**Comment by s-leger** [comment]
The axis constraint display depends on transform.translate operator (for snap), so i've no control of what happen in native operator.

**Comment by Moult** [comment]
Closing bug, as this is due to a default Blender behaviour, and will be resolved when CAD transform snap is implemented.
