### ISSUE TITLE
Archipack wall does not snap to vertex

### ISSUE THREAD

**Issue by Moult** [s-leger/archipack#195]
Archipack version: 2.3.1

Blender version: 2.83

Os version: Gentoo Linux

Description of the issue:

Note: I assume this is because Archipack hasn't yet been rewritten to use the new CAD transform snaps? So it is snapping to the axis of the other wall? If this is a work in progress and will be fixed when the new CAD transform snaps is factored, feel free to close this bug :)

In the attached file, I'm trying to snap to this point:

[archipack.zip](https://github.com/s-leger/archipack/files/5013115/archipack.zip)

![image](https://user-images.githubusercontent.com/88302/89134313-8cdf1780-d567-11ea-8f2f-84877d50c351.png)

However it seems to ignore the snap and snap to this point instead?

![image](https://user-images.githubusercontent.com/88302/89134317-95375280-d567-11ea-9d4a-84ed7a606728.png)

**Comment by s-leger** [comment]
In order to be able to snap, the walls must be all childs of the same reference point.
See [this video](https://youtu.be/fPtHkuiwY3E)

**Comment by Moult** [comment]
Thanks! Not a bug then :) Closed
