### ISSUE TITLE
Make objects safe to edit in free version in Blender 2.8

### ISSUE THREAD

**Issue by mocsa** [s-leger/archipack#197]
Archipack version: 1.2.83
Blender version: 2.83.4
Os version: N/A

Description of the issue:
Please add to the "Make objects safe to edit" page of the Wiki the information from [this Blender StackExchange answer](https://blender.stackexchange.com/questions/167765/archipack-tools-location) which tells that to make an object safe to edit you have to execute the command `C.active_object.data.archipack_XXXX.clear()` in the Python console. If you tell me how can I submit a pull request for the wiki, I'd also be happy to add it myself.

Also, I don't understand what you mean by "mesh tab" in the above answer. If you mean the "Object Data Properties" tab then I don't see any custom properties on that tab.

**Comment by s-leger** [comment]
Hi mocsa, 
repository for archipack 1.2.83 is blender's addon itself, you may provide a git diff right in https://developer.blender.org/
Maybe you can provide an operator to make them safe to edit.

```python
for key in o.data.keys():
    if "archipack_" in key:
       getattr(o.data, key).clear()
```
where o is the active object.

**Comment by mocsa** [comment]
Sorry, you misunderstood me.

I suggested you to update the Archipack documentation, which is the GitHub wiki, if I understand correctly.

I volunteered to update the documentation, not the Python code. I'm not a Python programmer.

**Comment by s-leger** [comment]
Ok, you should get invitation for collaboration.

**Comment by mocsa** [comment]
Thanks for the invite. I cleaned-up the above mentioned wiki page a little bit. Do you agree with the contents?

**Comment by s-leger** [comment]
Looks perfect to me, thank for the contribution !

**Comment by mocsa** [comment]
Thank you. Then we can close this issue.
