### ISSUE TITLE
Mesh chunking/splitting

### ISSUE THREAD

**Issue by pihdastudios** [s-leger/archipack#198]
Archipack version:

Blender version:
2.83

Os version:
Linuxmint 20

Description of the issue:
I've been enjoying your addon to make levels for my 3D game. But the engine doesn't necessarily handles large meshes properly. It would be nice to be able to split my meshes into x by x chunks like 
![Screenshot from 2020-08-18 05-54-36](https://user-images.githubusercontent.com/62319714/90452134-acee0980-e117-11ea-8bc8-1b9c3ae3c580.png)

Thanks.

**Comment by s-leger** [comment]
Archipack objects are regular blender mesh, so you are able to edit the way you like according your needs.
