### ISSUE TITLE
Upgrade to 2.8,x

### ISSUE THREAD

**Issue by 0x-Stealth** [s-leger/archipack#201]
Archipack version:
Newest one from here
Blender version:
2.80 and 2.90
Os version:
Windows
Description of the issue:
When I try use it it says Upgrade to 2.8.x required

**Comment by RayEbb** [comment]
I have the same issue.

**Comment by s-leger** [comment]
The addon in this repository require blender 2.79
For 2.8 either use archipack 1.2.8x (enable in addon preferences)
or [Order version 2.x on gumroad](https://gum.co/ZRMyP)
