### ISSUE TITLE
Bay Window bug on 2.3.2?

### ISSUE THREAD

**Issue by garethbradley** [s-leger/archipack#205]
Archipack version: 2.3.2

Blender version: 2.90.0

Os version: MacOS Catalina 10.15.4

Description of the issue:
When trying to add a bay window (3 sides) to the wall, Archipack "folds" the side windows in the opposite direction. See screenshot below.

This may be related to the fact that I had to flip some of the walls from outside/inside?

<img width="547" alt="Screenshot 2020-09-12 at 14 23 13" src="https://user-images.githubusercontent.com/450835/92996435-77182700-f503-11ea-88c8-9abdcb60f5ad.png">

**Comment by garethbradley** [comment]
Confirmed - this is related to walls where they are flipped inside out.

**Comment by s-leger** [comment]
This is an issue with "dead areas" of manipulators and bend code.
Take a look at[ this post for details](https://blenderartists.org/t/archipack-2-3-for-blender-2-8-release/1147328/263)
