### ISSUE TITLE
manipulate option is not showing

### ISSUE THREAD

**Issue by rohithreddy6799** [s-leger/archipack#206]
Archipack version:1.2.83

Blender version:2.9

Os version:

Description of the issue: manipulate option is not showing

**Comment by s-leger** [comment]
Select your archipack entity, then in right panel of 3d view, tab archipack there is a "manipulate" button near top of the panel.
Ensure the gizmos display is active in 3d view. 
Take a look at [The CG Essentials tutorial](
https://www.youtube.com/watch?v=l-aom9PyosM&t=515s)

**Comment by doublespy** [comment]
Same problem here with 1.2.84 on Blender 2.91.
Tried every possible option, but no luck. All the rest of the addon is working just fine.

**Comment by s-leger** [comment]
Fixed in 
https://developer.blender.org/rBA8ca8233069579b253dcfb881200321b99e1b612c
Maybe not backported to 2.91 series, use 2.92 instead.

**Comment by doublespy** [comment]
Downloaded 2.92, everything works fine now. Thanks for the quick answer !

**Comment by doublespy** [comment]
Even better ! @rohithreddy6799 : go to [this link](https://developer.blender.org/rBA8ca8233069579b253dcfb881200321b99e1b612c)
get the corrected version of archipack_manipulator.py and replace the one in your Blender addons.
Works now like a charm in my 2.91.
