### ISSUE TITLE
Wall auto-snap not visible in snap to options

### ISSUE THREAD

**Issue by AdelaLazur** [s-leger/archipack#207]
Archipack version: 2.3.2

Blender version: 2.90.1

Os version: Windows 10

Description of the issue: 
Wall auto-snap not available in snap to options. 
<img width="123" alt="1" src="https://user-images.githubusercontent.com/72267750/94940278-93d8c680-04d3-11eb-8428-33027907cc36.PNG">

**Comment by s-leger** [comment]
Wall auto-snap is available in wall's parameters.
For support requests of 2.3.x version please use the "Create->About->Support" button.
