### ISSUE TITLE
Hole or Windows don't follow wall

### ISSUE THREAD

**Issue by Marotte** [s-leger/archipack#208]
Archipack version: 2.3.2

Blender version: 2.9

Os version: Mac

Description of the issue: Windows or holes don't follow wall as described in [your video](https://www.youtube.com/watch?v=9F8m7ckNC-M).

In the video, the hole follows the wall:
![image](https://user-images.githubusercontent.com/1851429/95003021-87b23f00-058f-11eb-9377-58cf5852fd87.png)

In blender it does not:
![image](https://user-images.githubusercontent.com/1851429/95003027-a0225980-058f-11eb-9c49-0f1e1666d54e.png)

**Comment by s-leger** [comment]
I guess you are talking about 1.2.8x version.
Use square manipulators to move your wall.
For support requests of pro version, use Create->About->Support button.

**Comment by Marotte** [comment]
Apologies, previous issue submission was incomplete. Edited with more information....

**Comment by s-leger** [comment]
Select the wall, then manipulate using small arrows beside the hole axis.
