### ISSUE TITLE
Remove wall "part" modifies previous (lower numbered) part

### ISSUE THREAD

**Issue by photonclock** [s-leger/archipack#209]
Archipack version:1.2.83

Blender version:2.90

Os version:10.15.7

Description of the issue:
1. Create a wall
2. Add 3 additional "parts" to create a box/room shape (don't use "close")
3. Click "remove" on the last part/wall segment
Result: The angle and length on the part preceding the one removed gets adjusted to undesired values, ie, part 1,2,3,4. Delete part 4, part 3 angle gets set to a random angle and length gets set to a random length.

**Comment by s-leger** [comment]
When you press remove part, it will remove the first corner of the segment, between last part and current one.
