### ISSUE TITLE
Boolean problem with custom windows 

### ISSUE THREAD

**Issue by AdelaLazur** [s-leger/archipack#212]
Archipack version: 2.3.2

Blender version: 2.90.1

Os version: Windows 10

Description of the issue:

When I apply my custom into the wall it is cutting through, but the hole don't have inside faces. 

<img width="175" alt="1" src="https://user-images.githubusercontent.com/72267750/97787315-905b5c80-1bb1-11eb-8e36-ac0073fdf84e.PNG">

**Comment by s-leger** [comment]
Hi Adela, this is likely to be a boolean issue, where either 2 holes are too close or there is a coplanar face issue. Ensure your hole is slightly larger than wall, and there is no self-intersecting holes.
This issue will likely be solver in 2.91 version of blender with new boolean.

**Comment by onceadrog** [comment]
Seems to work with 2.3.4 in 2.92. I had previous issues with overlapping booleans in corners.
