### ISSUE TITLE
Une aide claire en français ? Ce serait bien. Merci !

### ISSUE THREAD

**Issue by Gilles3131** [s-leger/archipack#214]
Archipack version: 2.3.2

Blender version: 2.90.1

Os version: 10.15.7

Description of the issue:
Pourquoi ne pas proposer une aide VIDEO complète en français sur Youtube ? Cet Add on est super, mais on trouve bien trop peu d'infos claires et précises. C'est vraiment dommage. Merci par avance.

**Comment by onerawartist** [comment]
Its your chance to make a video about it ^^

**Comment by Gilles3131** [comment]
Hé hé… je participerais bien, le seul problème est que je suis débutant sur Blender. Je n'ai pas envie de raconter des salades !

**Comment by s-leger** [comment]
Il y a un [tutoriel complet en Français](https://youtu.be/_zImPoRr4TI) sur la chaine youtube, mais il est destiné à la version "pro". Les principes de base sont toujours applicables à la version "free".

**Comment by Gilles3131** [comment]
Merci Stéphane. J'utilise la version pro. J'ai regardé presque toutes les vidéos sur YT. Cet Ad on est génial, mais je trouve vraiment dommage de ne pas pouvoir trouver très rapidement une aide en français par sujet.
