### ISSUE TITLE
re install archipack pro

### ISSUE THREAD

**Issue by bigotes423** [s-leger/archipack#215]
Archipack version:

Blender version:

Os version:

Description of the issue:
I have several problems in drawing walls, connecting them, entering measures etc i decided to remove the pro version.
how can reinstall it again?
thanks

**Comment by mtonnie** [comment]
Not sure what the problem is.

Have you removed the addon from blender?
Do you need to download it again? If that's the case you will find the [link](https://blender-archipack.org/archipack/update) inside the [docs](https://blender-archipack.gitlab.io/setup.html)
