### ISSUE TITLE
Enter key won't work to draw a new segment 

### ISSUE THREAD

**Issue by bigotes423** [s-leger/archipack#218]
Archipack version: 2.0.9 pro
Blender version: 2.9

Os version: w10

Description of the issue:
I always get this error message
Traceback (most recent call last):
  File "C:\Users\Utente\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\archipack_20\__init__.py", line 734, in draw
    international = context.preferences.view.use_international_fonts
AttributeError: 'PreferencesView' object has no attribute 'use_international_fonts'

location: <unknown location>:-1

also when i draw a wall segment and break the operation and then i restart it is impossible to add new wall segments. also i get the error above.
very frustrating
 
thanks for help

**Comment by s-leger** [comment]
Download and setup latest archipack version (2.3.2) from official website, using the download e-mail or [request a download link through e-mail](https://blender-archipack.org/archipack/update)
Also. please use e-mail for archipack pro support, this git repository is for archipack 1.3.8 for blender 2.79
