### ISSUE TITLE
Using controls hides the controls

### ISSUE THREAD

**Issue by elkmug** [s-leger/archipack#219]
Archipack version: 1.2.84

Blender version: 2.9.1, 2.9.2

Os version: Win7 sp1 64-bit

Description of the issue:
Using specific interactive controls unintentionally hides the Archipack controllers.

Controls that cause this issue:
- interactive arrows for width, height, and thickness
- The interactive square that allows changing both angle and length at the same time

Controls that do NOT cause the issue:

- Clicking and changing numeric values in the 3D view
- Interactive arrows for changing angle
- Arrows for adding or removing sections
- Changing values in the Archipack sidebar properties panel

I've attached a small zipped video demonstrating both the controls that cause the issue and the ones that don't.

[archipack_controller_issue.zip](https://github.com/s-leger/archipack/files/5611053/archipack_controller_issue.zip)

Please note, this issue does not happen in a build of blender 2.8.1, which suggests it's probably a 2.9 and up issue

**Comment by s-leger** [comment]
Fixed this issue, will be in next buildbot and upcoming blender's releases.
Thank you for reporting.
