### ISSUE TITLE
Worflow for 2d to 3d

### ISSUE THREAD

**Issue by s-leger** [s-leger/archipack#22]
Creating doors and windows from either polygons or point selection tool, as follow.
1 Select either points or polygon tool - depends on tool choosen to do so.
2 use W for Window and D for Doors to enter orientation mode
3 Click drag to set orientation, release to create object and return in select mode
Esc or right to exit

**Comment by mirlip** [comment]
Will be a very fast new workflow and it follows the select, call tool with shortcut principle of Blender :)

**Comment by s-leger** [comment]
Done,
Push on geos branch will follow soon
