### ISSUE TITLE
Windows and Doors "freezes" in the creation window

### ISSUE THREAD

**Issue by ThiagoRieth** [s-leger/archipack#220]
Archipack version: 2.3.3

Blender version: 2.83, 2.9, 2.91

Os version: Windows 10

Description of the issue: Everytime I am tryi to create a Door or Window it lock me inside the creation blue bar. "Enter" does not work, the manipulate arrows do not appear. It simply stays in creation mode locked. I am able to press Shift A or access the create panel and create another object (stairs, for example) it works fine. But if I try to select the window or door again it still locked with the "create window/door" blue box. Only way out is to press right click to abort this. Versions 1.x.x worked fine.

**Comment by s-leger** [comment]
Hit esc to exit from "draw" tool.
By the way, use "Create-->About->support" for support request for archipack pro.

**Comment by ThiagoRieth** [comment]
Hi, tks for the fast response.

But it still does not solve the problem.
If I hit "esc" it deletes the door or the window.

Only way around I found to solve this was to create a wall, drag the door/window there and then deleted the wall.

In the 1.x.x versions I could simply create a door or a window anywhere and it would be "operational".
In this 2.x.x It only works after dragging it to a wall.

I don't know if this is a different approach in the 2.x.x versions or if I am missing something. Just started to use the 2.x.x. version today.

Tks in advance.

________________________________
De: s-leger <notifications@github.com>
Enviado: sexta-feira, 18 de dezembro de 2020 16:32
Para: s-leger/archipack <archipack@noreply.github.com>
Cc: ThiagoRieth <thiago.rieth@hotmail.com>; Author <author@noreply.github.com>
Assunto: Re: [s-leger/archipack] Windows and Doors "freezes" in the creation window (#220)


Hit esc to exit from "draw" tool.
By the way, use "Create-->About->support" for support request for archipack pro.
