### ISSUE TITLE
adding the mesh (from archipack) freezes Blender

### ISSUE THREAD

**Issue by Mona555-oss** [s-leger/archipack#221]
Archipack version: 1.2.84

Blender version: 2.91.0

Os version: windows 10, 64

Description of the issue: when I try to add a window or a door, it gives me the same shape of a strange rectangle with (x) sign and the whole program freezes!

**Comment by s-leger** [comment]
https://www.youtube.com/watch?v=l-aom9PyosM

**Comment by Mona555-oss** [comment]
> https://www.youtube.com/watch?v=l-aom9PyosM

Thanks a lot!  That solved the problem
