### ISSUE TITLE
Autosynchro not working on walls

### ISSUE THREAD

**Issue by Walkion** [s-leger/archipack#222]
Archipack version:2.3.3

Blender version: 2.83

Os version: Windows 10

Description of the issue: When using the function "auto synchro" on walls, the floor molding do not adjust as expected when moving doors and large windows (reaching floor level). User has to delete moldings and re-generate them so that it takes in account the changes made on openings' locations.

https://user-images.githubusercontent.com/76704593/103238823-27435b80-494c-11eb-9ff1-12e92d33753a.mp4

**Comment by s-leger** [comment]
Select the wall, it will provide manipulators for windows size and location with the auto-synchro feature.
By the way, use 
Create->About->Contact support  
for 2.x version
