### ISSUE TITLE
Archipack won't render preview thumbs

### ISSUE THREAD

**Issue by jmpreston** [s-leger/archipack#223]
Archipack version:
1.2.84

Blender version:
2.91

Os version:
Mac OS Big Sur 11.0.1

Description of the issue:

In Edit / Preferences / Add-ons / ArchiPack I've clicked Render Presets Thumbs twice and I get the spinning umbrella that indicates the computer is struggling.  I understand that instead it should bring up the terminal and that isn't happening.  Eventually the umbrella goes away and when I try to add a window or whatever to a wall there are no presets.

This is the free version that comes with Blender.  If I can get this to work I would probably be interested in the paid version.

I have tried this on a 2016 MacBook Pro with 16 GB of RAM and a 2020 Mac mini M1.  So this seems to be an issue of launching the terminal.  The terminal now is ZSH, not Bash, if that makes a difference.

**Comment by s-leger** [comment]
Restart blender once done.

**Comment by jmpreston** [comment]
Thanks!  That did it.  The tutorial I was watching about setting up ArchiPack didn't show or explain that.
