### ISSUE TITLE
Boolean / Holes dont apply

### ISSUE THREAD

**Issue by randomspawn42** [s-leger/archipack#224]
Archipack version:
Pro 2.3.3

Blender version:
2.91.0 & 2.83

Os version:
Win10

Description of the issue:

Tried to apply all booleans and cleanup holes-objects (for export) according to [https://blender-archipack.gitlab.io/user/archipack%20tools.html](https://blender-archipack.gitlab.io/user/archipack%20tools.html)

After deleting all hole-objects no boolean seem to be applied.

![01](https://user-images.githubusercontent.com/76846649/103443791-d04ac880-4c62-11eb-80f9-99ef471a72b8.png)
Auto Boolean clicked

![02](https://user-images.githubusercontent.com/76846649/103443795-d50f7c80-4c62-11eb-92ff-39f160b49ade.png)
After deleting holes

**Comment by s-leger** [comment]
Use "tools->apply holes"

**Comment by randomspawn42** [comment]
https://user-images.githubusercontent.com/76846649/103576193-0f7f5080-4ed3-11eb-8182-045f4e8f1944.mp4

The Tools-Tab is empty for me

**Comment by s-leger** [comment]
Expand the tools panel (small arrow)

**Comment by randomspawn42** [comment]
Now I feel stupid.
