### ISSUE TITLE
I really wish there would be an option to add custom exterior walls. and also I would like to use modifiers on walls, windows, doors and the rest of objects because everything looks too sharp

### ISSUE THREAD

**Issue by Ruumi** [s-leger/archipack#225]
Archipack version:

Blender version:

Os version:

Description of the issue:

**Comment by Ruumi** [comment]
Also I would love to show the structure of a house I'm working on. Like showing the framing insulation and stuff

**Comment by s-leger** [comment]
Archipack pro provide custom finishings, composite walls are not yet available, but probably will be implemented in the future.
