### ISSUE TITLE
Crash when creating a wall

### ISSUE THREAD

**Issue by EndEffected** [s-leger/archipack#228]
Archipack version: 2.0.9

Blender version: 2.91.0

Os version: Windows 10 (up to date)

Description of the issue: i have crashes when i try to create a wall

![image](https://user-images.githubusercontent.com/14148136/104829342-0c8d4400-5873-11eb-98dd-fb45e497411d.png)

i can't do anything with the addon, everythig cause crashes or this issues, what i do false ?

**Comment by s-leger** [comment]
Take a look at your e-mail, you should find a donwload link for latest version (2.3.3) . Once downloaded and setup, restart blender.
