### ISSUE TITLE
can't load the thumbnails

### ISSUE THREAD

**Issue by julpa** [s-leger/archipack#231]
Archipack version:

Blender version:2,912 , tried with 2,79 but same problem

Os version: mac os 10.14.6 (18G7016)

Description of the issue:
can't load the thumbnails, don't have filmic addon, so I can not use anything else than the walls 
when clicking on the windows, ii get a dark blank page 
when i try to load the thumbnails from preferences, i get a spiral but nothing seems to happen :(

**Comment by s-leger** [comment]
Restart blender once done.
