### ISSUE TITLE
Wall UVs don't join propery with next section of the wall

### ISSUE THREAD

**Issue by radiantzero** [s-leger/archipack#232]
Archipack version: 2.3.3

Blender version: 2.8 and 2.9

Os version: win10 
Description of the issue: Wall UVs don't join propery with next section of the wall
![uvs](https://user-images.githubusercontent.com/10908470/108933293-d919b280-7685-11eb-91c4-cfd5b9555a16.jpg)

Please fix this since makes the autogenerated UVs pretty useless if we can't tile the texture along the walls

**Comment by s-leger** [comment]
With metric based tile size and objects not being simple cubes discontinuity are unavoidable.

**Comment by radiantzero** [comment]
I think you've misunderstood this :
Each single part of the wall comes out split into a sepasrated UV island .
In the picture I've moved the islands apart to make it more visible , but they are all separated and often even partially overlapped.
To be of any use it should be one single island of all sections merged and lined up in a raw .
**And this is exactly how you have done it with the mouldings,** so obviously it is possible to do it procedurally , since you have done it already with the mouldings.

![uv](https://user-images.githubusercontent.com/10908470/108995338-e8295080-76d7-11eb-908c-b29d4d688c9d.jpg)

**Comment by s-leger** [comment]
If you take a close look at moulding uvs, top and bottom faces are stretched, it does work ok with wood texture, but it may be an issue with tiles.
Wall use another unwrap method able to cope with height changes across segments, where procedural method will simply fail with huge deformations. Top and bottom are also unwrapped apart (top projection). 
I agree that keeping track of each segment length for each side of wall would allow to provide a single island for each wall side and keep continuity between segments, but there are little to no cases (to my knowledge) where it is relevant for real world wall's textures.

**Comment by radiantzero** [comment]
I understand and this is really unfortunate .
Having one continous island woud be really beneficial if applying any tiled type of texture like exposed bricks or feature walls .
Also the lightmaps that comes out of this walls are a nightmare since real time rendering engines ( like unreal engine 4) creates the necessary UVs for lightmaps based on the existing UV islands  of the imported model.
