### ISSUE TITLE
"120x110 flat 2 round" window default model has extra handle in wrong position

### ISSUE THREAD

**Issue by onceadrog** [s-leger/archipack#234]
Archipack version: 2.3.4

Blender version: 2.92

Os version: Windows 10, version 20H2

Description of the issue: 
Default model for window named "120x110 flat 2 round" has an extra handle embedded in the top left corner of the wall on creation.
![image](https://user-images.githubusercontent.com/6299372/110249244-e57df500-7f3a-11eb-9a8e-90debd3b4faf.png)

Handle is parented to the upper curved section of window.
![image](https://user-images.githubusercontent.com/6299372/110249231-d5661580-7f3a-11eb-960c-5a92bdb54493.png)

**Comment by s-leger** [comment]
You are right, something is plain wrong here. 
You may set top foil type to "fixed" so it will no more generate the handle.
