### ISSUE TITLE
I can't use the walls.

### ISSUE THREAD

**Issue by Paru84** [s-leger/archipack#236]
Archipack version: 20.9

Blender version: 2.9.2

Os version: Windows 10 Pro

Description of the issue: I can't use the wall option. It said: Python Traceback
!
![issue](https://user-images.githubusercontent.com/80966686/111792933-09d7bb00-88c5-11eb-9d77-0b85ba5d8500.png)

**Comment by s-leger** [comment]
Hi Paru,
Download latest version (2.3.4) using the link in blender-archipack.org e-mail, or contact support@blender-archipack.org
