### ISSUE TITLE
Archipack on Mac 

### ISSUE THREAD

**Issue by spike38** [s-leger/archipack#238]
Archipack version: 1.2.83

Blender version: 2.82a

Os version: Mac OS 10.14.6

Description of the issue: I cannot get the plug in to activate I've tried rendering the thumbnails in blender prefs but nothing happens, downloaded the latest release of blender say issue there it won't load many thanks

**Comment by s-leger** [comment]
Restart blender once thumb rendering done.

**Comment by spike38** [comment]
I did try that after reading it but you can see
The assets are still not in the add menu
Like they should be I have tried in this version and the very latest version of blender also



Regards mike



Regards
Mike

Shock the senses 
2 Old Brew House, Bow Street, Guisborough, TS14 6PR
Tel: 01287 638887 | Skype: mikenshock | Email: ***@***.*** | Visit: www.shockthesenses.com

NEW - Download & Upload Large Files through our FTP Server.
http://www.shockthesenses.com/ftp/ <http://www.shockthesenses.com/ftp/>

The information in this email is confidential and may be legally privileged. It is intended solely for the addressee. Access to this email by anyone else is unauthorised. If you are not the intended recipient, any disclosure, copying, distribution or any action taken or omitted to be taken in reliance on it, is prohibited and may be unlawful.

If your company does not consent to email of this nature please advise us. Opinions expressed in this message are not necessarily those of the company.

Please note that the company cannot be held responsible for viruses and it is your responsibility to scan any attachments.

**Comment by s-leger** [comment]
Any error in the blender's console while rendering ?
You also may use the right panel of 3d view -> Create tab.  (n shortcut to show the right panel)

**Comment by spike38** [comment]
NO errors at all just ran it again

Get the spinning beach ball for a couple of mins
Thats it





Regards
Mike

Shock the senses 
2 Old Brew House, Bow Street, Guisborough, TS14 6PR
Tel: 01287 638887 | Skype: mikenshock | Email: ***@***.*** | Visit: www.shockthesenses.com

NEW - Download & Upload Large Files through our FTP Server.
http://www.shockthesenses.com/ftp/ <http://www.shockthesenses.com/ftp/>

The information in this email is confidential and may be legally privileged. It is intended solely for the addressee. Access to this email by anyone else is unauthorised. If you are not the intended recipient, any disclosure, copying, distribution or any action taken or omitted to be taken in reliance on it, is prohibited and may be unlawful.

If your company does not consent to email of this nature please advise us. Opinions expressed in this message are not necessarily those of the company.

Please note that the company cannot be held responsible for viruses and it is your responsibility to scan any attachments.

**Comment by spike38** [comment]
Seems odd

As I have not had an issue installing any other plug in at all

Also it does the same thing in blender 2.92 if this helps






Regards
Mike

Shock the senses 
2 Old Brew House, Bow Street, Guisborough, TS14 6PR
Tel: 01287 638887 | Skype: mikenshock | Email: ***@***.*** | Visit: www.shockthesenses.com

NEW - Download & Upload Large Files through our FTP Server.
http://www.shockthesenses.com/ftp/ <http://www.shockthesenses.com/ftp/>

The information in this email is confidential and may be legally privileged. It is intended solely for the addressee. Access to this email by anyone else is unauthorised. If you are not the intended recipient, any disclosure, copying, distribution or any action taken or omitted to be taken in reliance on it, is prohibited and may be unlawful.

If your company does not consent to email of this nature please advise us. Opinions expressed in this message are not necessarily those of the company.

Please note that the company cannot be held responsible for viruses and it is your responsibility to scan any attachments.

**Comment by spike38** [comment]
All sorted now 


user error I thought that the menu was accessible through the -> add menu

When its -> Add  ->Mesh 

Sorry for this

Have a great weekend




Regards
Mike

Shock the senses 
2 Old Brew House, Bow Street, Guisborough, TS14 6PR
Tel: 01287 638887 | Skype: mikenshock | Email: ***@***.*** | Visit: www.shockthesenses.com

NEW - Download & Upload Large Files through our FTP Server.
http://www.shockthesenses.com/ftp/ <http://www.shockthesenses.com/ftp/>

The information in this email is confidential and may be legally privileged. It is intended solely for the addressee. Access to this email by anyone else is unauthorised. If you are not the intended recipient, any disclosure, copying, distribution or any action taken or omitted to be taken in reliance on it, is prohibited and may be unlawful.

If your company does not consent to email of this nature please advise us. Opinions expressed in this message are not necessarily those of the company.

Please note that the company cannot be held responsible for viruses and it is your responsibility to scan any attachments.
