### ISSUE TITLE
out frames's depth influence width

### ISSUE THREAD

**Issue by mirlip** [s-leger/archipack#24]
When you set a depth for the out frames, it will also change the width. The width parameter then only has an effect if it's value is higher than the depth. Correcting this would allow to have thin out frames.

**Comment by s-leger** [comment]
In order to get thin out frames, use a small depth, and increase width.

With a width set to less or equal than depth, you may use "offset" to get negative joints arround frame (only visible after boolean as it does affect hole).

**Comment by mirlip** [comment]
I tried many combinations but couldn't get something like that http://3.bp.blogspot.com/_4zN2YcMsVMM/S-_dZJnlxjI/AAAAAAAABac/I6Vyj26feC8/s1600/PICT0056.JPG

**Comment by s-leger** [comment]
Ok, have to separate depth of side and front part of outer frame.
