### ISSUE TITLE
Wall with User Definied Finish Texture, Displacement and Bump Issues.

### ISSUE THREAD

**Issue by 4lex4rch** [s-leger/archipack#241]
Archipack version: 2.3.4

Blender version:2.92.0

Os version:Ubuntu 20.10

Description of the issue:User Defined Wall Finish does not display texture like other finishes. For me a blank white texture is all I can get regardless of the texture of the User Defined Object to be used as Finish.  It also can't show displacement or use adaptive subdivision. This would be very helpful for showing textures and especially corrugated siding.  

Thanks. I love this addon!

**Comment by s-leger** [comment]
In finish settings, you'll find a dropdown list to actually assign material to finish. The list contains names of materials wich belong to the wall. You may add a new material as you would do with regular blender editing and use the list to assign material to that perticular finish.
