### ISSUE TITLE
Floors glitchy

### ISSUE THREAD

**Issue by dingsboms** [s-leger/archipack#242]
Archipack version: 
PRO 2.0.9

Blender version: 
2.92
Os version: 
Windows 10
Description of the issue:
I can't seem to create any floor. Either if i try to create floor from wall or just add it as a mesh the floor goes in crazy directions and very far out, leading to crash blender.

**Comment by s-leger** [comment]
You must update to latest archipack version 2.3.4 using link in e-mail from blender-archipack.org or contact support@blender-archipack.org
