### ISSUE TITLE
Failed to create Walls, they cannot be created.

### ISSUE THREAD

**Issue by jaby07** [s-leger/archipack#244]
Archipack version: 2.0.9

Blender version: 2.92.0

Os version: Windows10 Pro 20H2

Description of the issue: I get this Error when creating Walls, windows, and other elements and they cannot be created. How can i fix it? I just bought this addon and have not been able to use it yet. Please help.

![error blender arhipack_Mesa de trabajo 1](https://user-images.githubusercontent.com/82460481/116196631-07724780-a734-11eb-8b12-02c648cde6a9.jpg)

**Comment by s-leger** [comment]
Downlaod latest version using link found in e-mail from blender-archipack.org or contact support@blender-archiapck.org
