### ISSUE TITLE
Door handle components.

### ISSUE THREAD

**Issue by onceadrog** [s-leger/archipack#250]
Archipack version: 2.3.4

Blender version: 2.9.2

Os version: Windows 10 Build 19041

Description of the issue:

Door handles are static single piece meshes, but for animating door handle movement, they need to be split into the fixed part, and the moving part of the handle. this can add up to a lot of dot clicking to lock them down.
Also, origins need to be manually reconfigured in Blender for door, window pane, handle, etc before exporting to unreal, so all the parts line up nicely.

Can they please be modelled as two meshes? One for the handle base, and one for the moving part for ease of animation.

Adjusting origins vs parenting is a trickier fix, but not as fiddly to do manually as remodelling door handles...

**Comment by onceadrog** [comment]
I now have a standard library in Unreal with all my standard door and window actors, but it is still an issue for animating stuff in Blender.

**Comment by s-leger** [comment]
Will be fixed in 2.3.6, custom handles allow complex parent-child objects.
