### ISSUE TITLE
After installing archipack pro and the preset aren't rendering

### ISSUE THREAD

**Issue by Eddiet1983** [s-leger/archipack#252]
Archipack version:

Blender version:2.93

Os version: windows

Description of the issue:
I have a problem with archipack pro. the textures are missing. I have always this error message

![Error install](https://user-images.githubusercontent.com/85662382/121466827-5e686f00-c9b8-11eb-8d4e-8098b6a09c57.JPG)

**Comment by s-leger** [comment]
Hi Eddiet,
You must download latest version (2.3.4) using link found in e-mail from blender-archipack.org.
