### ISSUE TITLE
Blender Quits on Window Preset Saving

### ISSUE THREAD

**Issue by WhiteX** [s-leger/archipack#254]
Archipack version: 2.3.4

Blender version: 2.93

Os version: Windows 10

Description of the issue: Blender quits when I try to save a window preset.
Error log:

[log]### RENDER THUMB ############################
Info: Deleted 3 object(s)
Info: Deleted 3 object(s)
[log]Start generating: window
[log]Prepare camera
[log]Prepare scene
[log]Render
Fra:1 Mem:22.79M (Peak 23.05M) | Time:00:01.79 | Syncing Camera
Fra:1 Mem:22.79M (Peak 23.05M) | Time:00:01.79 | Syncing Plane
Fra:1 Mem:23.16M (Peak 23.51M) | Time:00:01.80 | Syncing Point
Fra:1 Mem:23.16M (Peak 23.51M) | Time:00:01.80 | Syncing Point.001
Fra:1 Mem:23.16M (Peak 23.51M) | Time:00:01.80 | Syncing Point.002
Fra:1 Mem:23.16M (Peak 23.51M) | Time:00:01.80 | Syncing Window
Fra:1 Mem:39.99M (Peak 55.40M) | Time:00:01.92 | Syncing Window Panel
Fra:1 Mem:40.01M (Peak 55.40M) | Time:00:01.92 | Syncing Window glass
Fra:1 Mem:40.02M (Peak 55.40M) | Time:00:01.92 | Syncing Handle
Fra:1 Mem:40.42M (Peak 55.40M) | Time:00:01.97 | Rendering 1 / 65 samples
Fra:1 Mem:40.00M (Peak 55.40M) | Time:00:02.31 | Rendering 26 / 64 samples
Fra:1 Mem:40.00M (Peak 55.40M) | Time:00:02.34 | Rendering 51 / 64 samples
Fra:1 Mem:40.00M (Peak 55.40M) | Time:00:02.35 | Rendering 64 / 64 samples
Saved: 'C:\Users\[Username]\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\presets\archipack_window\velux.png' Time: 00:02.72 (Saving: 00:00.36)

[log]### COMPLETED ############################

Blender quit

Edit: The preset was saved successfully though. After closing the log window, Blender quits, but upon restart the new preset is there.

**Comment by s-leger** [comment]
Archipack run a background instance of blender in order to render thumbnails, so it is epected that blender quit the background instance once render done.
You may hide the console by selecting main blender window again, but do not close that console as blender main windows depends on it.
