### ISSUE TITLE
REQ: Change the tab menu name from 'create'

### ISSUE THREAD

**Issue by quadcom** [s-leger/archipack#255]
Archipack version: All

Blender version: 2.92

Os version: Win10

Description of the issue: Since the beginning (afaik) the N menu tab for Archipack simply says 'create'. Can this be updated to 'Archipack'? All the other addons that populate this section use their name. Just thought it would be a little more clear and easy to find.

**Comment by s-leger** [comment]
You are able to choose tab name in preferences.
