### ISSUE TITLE
I cannot create doors, windows ... Or any elements with the "blue banner"

### ISSUE THREAD

**Issue by Ciupcic** [s-leger/archipack#256]
Archipack version: 2.3.5

Blender version: 2.93.0

Os version: Windows 10 Pro 20H2 (build 19042.1052)

Description of the issue: 
When creating a door (as an example) I can't do anything except cancel my action with Escape or right click. None of the actions described in the blue bannner have any effect. The door is "created" but I cannot interact with it and it disappears once I press Escape (or right click).
Maybe I'm not doing it right, but I don't see how else to do it.

**Comment by s-leger** [comment]
Draw tools expect a wall !
So first create a wall, then draw your doors / windows over walls.
Please rely on e-mail to support@blender-archipack.org for support requests for archipack "pro".

**Comment by Ciupcic** [comment]
Thank you for the quick reply. Indeed I was telling myself that I had missed a step ^^
I wanted to do as with Archipack Lite and create the door directly.

Very good tool that I can't wait to master :)
