### ISSUE TITLE
Handles for Rail window

### ISSUE THREAD

**Issue by ACWesterberg** [s-leger/archipack#258]
Archipack version: 2.3.5

Blender version: 2.93.0

Os version: Windows

Description of the issue:
1. Tried to make a rail window, first of all the handle looks strange. The handle seems to be like 30 cm long for some reason.

2. Also, there are handles on either side of the rail window and no option to change that.

3. On a 3 rail window, the handle is placed on the left-hand side of the furthest window. Which I find strange. On a 2-rail window, the handle is therefore in the middle. This results in opening the window you will have a handle clipping through the fixed window. Usually the handle would be placed closest to the wall for a rail window.

**Comment by s-leger** [comment]
1 Handles like that are common for "tilting and sliding" windows.
2 Agree this is plain wrong.
3 You are definitively right.

**Comment by ACWesterberg** [comment]
1. Are you sure? I attach an image of the standard 180x210 2 Rail window preset from the plugin. They look elongated

![Rn9dwMv](https://user-images.githubusercontent.com/70880181/124933364-1e6ec900-e004-11eb-875e-e67360db6d8d.png)

**Comment by s-leger** [comment]
![portes-coulissantes-a-translation](https://user-images.githubusercontent.com/7442572/124934672-38f57200-e005-11eb-9241-780cac98b581.jpg)
![poignee3](https://user-images.githubusercontent.com/7442572/124935116-a3a6ad80-e005-11eb-9bfc-65cd61383ca9.jpeg)
![poignee2](https://user-images.githubusercontent.com/7442572/124935118-a43f4400-e005-11eb-96fa-5be5cf1d0451.jpeg)
![poignee1](https://user-images.githubusercontent.com/7442572/124935121-a4d7da80-e005-11eb-81ed-312cf1ab2030.jpeg)

**Comment by s-leger** [comment]
By the way, you are able to use custom geometry for handle.

**Comment by ACWesterberg** [comment]
Yeah I did just that! Thanks! I'll let you know if I find any other issues going forward and will add those in as new. Love the plugin!

**Comment by s-leger** [comment]
Fix available in beta 2.3.94+
