### ISSUE TITLE
Can't create window on polygon (2d to 3d) 

### ISSUE THREAD

**Issue by monstrue** [s-leger/archipack#259]
Archipack version: 2.3.5

Blender version: 2.93.1

Os version: macOS Big Sur 11.4

Description of the issue: when I try to create s new window after selecting the polygon typing w and clicking and dragging with the left mouse button, I get the following error message when I release the mouse button: "AttributeError: bpy_prop_collection: attribute "handle_altitude" not found"

https://user-images.githubusercontent.com/8113400/125193746-66812c00-e24e-11eb-8cba-67822af79455.mov

<img width="840" alt="ArchipackwindowERROR" src="https://user-images.githubusercontent.com/8113400/125193628-b3183780-e24d-11eb-9988-2a4d251596a4.png">
"

**Comment by s-leger** [comment]
This is a known reported error, will push hotfix release soon.
In the meantime, use regular "draw window / doors tools" once walls are done.

**Comment by monstrue** [comment]
Merci Stephen. Any idea when the hotfix will be available?

**Comment by s-leger** [comment]
Released 2.3.6
