### ISSUE TITLE
Windows handles outside

### ISSUE THREAD

**Issue by MaSchl74** [s-leger/archipack#261]
Archipack version:  2.3.6

Blender version: 2.93.1

Os version: Win 10

Description of the issue: Window handles sometimes are created outside, or even on both sides.

**Comment by s-leger** [comment]
Walls do have inside and outside, so if you find yourself with handles on the outside, you must select the wall and use "flip in/out" in  wall's parameters AXIS tab.
By the way, use support@blender-archipack.org for support of archipack PRO, this repo is archipack lite one.
