### ISSUE TITLE
No repositioning widget for windows

### ISSUE THREAD

**Issue by MaSchl74** [s-leger/archipack#262]
Archipack version:  2.3.6

Blender version: 2.93.1

Os version: Win 10

Description of the issue: Windows can't be moved along walls. In tutorials, there's a widget in the center on the bottom, I only have windows width arrows.  Edit: of course, also height etc., dimensions all work fine. but no horizontal repositioning.

**Comment by s-leger** [comment]
The "relocate" widget is a wall's one, so select the wall.
NOTE: you must enable "Auto-synch" for this feature to work in 2.3.5+, next release will adress this issue.

**Comment by MaSchl74** [comment]
Aut Synchro did the job! Thank you!
