### ISSUE TITLE
Windows array demands "drawing object over wall"

### ISSUE THREAD

**Issue by MaSchl74** [s-leger/archipack#263]
Archipack version:  2.3.6

Blender version: 2.93.1

Os version: Win 10

Description of the issue: I draw a window, I don't get an array. Maybe because the wall corner angles aren't 90 degrees? I need to precisely arrange windows, which won't work well with "G", as the walls aren't following straight X/Y axis. Drawing another linked window works fine, they both are linked, also the following ones, but since I have no way to reposition them on the wall, an array would help tremendously.

**Comment by s-leger** [comment]
In order to use "array" operator, you need to first add a single window on the wall, then exit the draw tool.
Select the window and you'll find "array" tool at top of windows pareameters.
