### ISSUE TITLE
unable to get the floor points move

### ISSUE THREAD

**Issue by doctorate75** [s-leger/archipack#265]
Archipack version: 1.2.83

Blender version: 2.82 (sub 7)

Os version: Ubuntu 20.04

Description of the issue:
cannot move the handles of the floor element after being added via Archipack addon. I cannot move the dots at the corners of the floor nor could I get arrow heads move either. The only way I can change the dimension of the floor is by entering the number shown on the dimension of the floor which isn't quite useful in many cases where you need to do snapping most of the time.

![Blender-floor-bug-short-version](https://user-images.githubusercontent.com/29259472/128565830-157f6cd3-f1a3-4a57-89ac-24c91f47420d.gif)

**Comment by s-leger** [comment]
In order to move corners manipulators, hover the square, press and keep your mouse pressed while moving.
Archipack's objects are not ment to be modified in edit mode, any subsequent manipulation or parameter change will reset your changes.
