### ISSUE TITLE
Image Rotation Bug

### ISSUE THREAD

**Issue by Macker19** [s-leger/archipack#266]
Archipack version:1.2.84

Blender version:2.92

Os version: Windows 10

Description of the issue: Screens image 3D axis rotation (upper right corner)  doesn't work at all when using Archipack. Does anyone have encountered this sort of a bug before?

**Comment by s-leger** [comment]
Archipack draw tools are "blocking" (and so are blender's own transform tools) meaning you can't change point of view while active.
