### ISSUE TITLE
Text size is too small

### ISSUE THREAD

**Issue by starksm64** [s-leger/archipack#271]
Archipack version: 1.2.84

Blender version: 2.93.4

Os version: OSX 10.15.7

Description of the issue: The text size on the dimension are too small to be readable. I have scaled the blender interface and text size to make them visible easily on a 27-inch (5120 x 2880) retina display, but the Archipack text has not scaled up, and it is virtually unreadable. Attached is an image of the screen after adding a wall where I have used the tape measure tool to show the size of text blender is using vs what Archipack is using.

<img width="1405" alt="apack_textsize" src="https://user-images.githubusercontent.com/332210/133004795-e649dee3-8f03-4251-81b9-448aeea18dd1.png">

**Comment by s-leger** [comment]
Font size is configurable in addon preferences.
