### ISSUE TITLE
The archipack don't load the useful elements

### ISSUE THREAD

**Issue by Eduardo12X** [s-leger/archipack#273]
Archipack version:
1.2.84
Blender version:
2.93.104.0
Os version:
Windows 11
Description of the issue:
When I want to select any object (door, floor, window, etc), appear the default window, but that window doesn't load or load, however it doesn't appear anything to select and I just exit that window when I click on the right mouse button, I test the pirate version, because I don't want spend money only about it, and the pirate version of the pro version functioned. OBS: i don't recommend that you use the pirate version of the archipack:

![Screenshot 2021-10-05 105309](https://user-images.githubusercontent.com/85649279/136039522-3e885934-182c-42b6-83ff-57ff9bb4177b.png)

**Comment by s-leger** [comment]
You are just 1 click away from solution
https://github.com/s-leger/archipack/wiki#setup-128x-for-blender-28

**Comment by Eduardo12X** [comment]
Depending on your machine, it delays rendering the objects and the blender can't load and crash in the rendering in this period, but thanks of it
