### ISSUE TITLE
Problem with slab cutter

### ISSUE THREAD

**Issue by GigaBite2001** [s-leger/archipack#274]
Archipack version: latest

Blender version: latest

Os version:
Description of the issue: explained in video https://drive.google.com/file/d/10OI8jvhUQaQJ-Hxm7OQRjPGr11kXBCAf/view?usp=sharing

**Comment by s-leger** [comment]
Hi, 
Thank you for your report !
Looks weired as slab cutter should not interfer with reference point location, had no direct answer for this problem, but definitely will take a look at it.
