### ISSUE TITLE
Draw error

### ISSUE THREAD

**Issue by BeatScherrer** [s-leger/archipack#275]
Archipack version: 2.0.9

Blender version: 2.93.5

Os version: Arch Linux

Description of the issue:

when trying to add an item from the object create menu I get the following error:
![2021-10-23-143233_1916x2060_scrot](https://user-images.githubusercontent.com/24778752/138556368-19cfe6d8-60f4-4af0-bdb3-189b4c46a855.png)

unfortunately I could not find the error in text and therefore I just created the screenshot

**Comment by s-leger** [comment]
Take a look at your e-mails from blender-archipack.org  you should find download link for latest version (2.3.6).
Once downloaded, setup over and rerstart blender.
