### ISSUE TITLE
Archipack Walls Broken in Edit Mode

### ISSUE THREAD

**Issue by winterbrass** [s-leger/archipack#276]
Archipack version: 1.2.84

Blender version: 2.93

Os version: Windows 10 20H2 build 19042.1288

Description of the issue:
24 hours ago, Archipack was working perfectly fine. Now, when I select a wall and enter edit mode, only one particular face (or group of faces, in the case of walls that have been extended) can be edited or manipulated and the vertexes attached to the other face are missing. It first appeared in a particular blend file after loading and now the problem occurs in all new files created. I've searched thoroughly for a resolution and I am beyond frustrated. I'm hoping that it's something stupid that I've done because this problem has completely prevented me from moving forward with a project that I'm working on.
![blenderIssue](https://user-images.githubusercontent.com/13858316/138621260-5982baf0-dff7-46cd-9177-eaf2833f141e.PNG)

**Comment by winterbrass** [comment]
I sent the blend file to a friend to confirm whether this was localized to my machine, and now she has the same issue that I do - and it's affecting her blends that were created prior to me sending her the file.

**Comment by winterbrass** [comment]
I've used Revo Uninstaller to remove all files and registry references to Blender and Archipack and the problem persists. Please contact me at my username at gmail so I can attach the problematic blend file.

**Comment by s-leger** [comment]
Archipack 1.2.8x walls are single sided and use a solidify modifier, so you are not able to edit faces generated by the modifier.
If you want to keep archipack's features, you should never edit those objects in edit mode as any subsequent change in parameters will revert your changes.
