### ISSUE TITLE
Missing Scripts Files

### ISSUE THREAD

**Issue by akmaltong** [s-leger/archipack#280]
Archipack version: 2.3.3

Blender version: 3.0

Os version: Windows 10

Description of the issue: 
![2021-11-30_16-26-32](https://user-images.githubusercontent.com/40340558/144061909-b91e0413-1d2d-4f73-9e97-085e1cc68316.png)

**Comment by s-leger** [comment]
Archipack free was removed from blender 3.0
Looks like you are using outdated archipack's pro version ..
Both should never be enabled together.
