### ISSUE TITLE
Unable to drag or move windows or doors after adding into scene.

### ISSUE THREAD

**Issue by n-techSg** [s-leger/archipack#290]
Archipack version:
2.4.0
Blender version:
3.0
Os version:
Windows 10 Pro 21H2
Description of the issue:
Unable to drag or move any windows or doors after adding to the scene. 

![2022-01-01 16_27_35-Blender](https://user-images.githubusercontent.com/65995010/147846919-a4b5768e-fe95-4437-a6cc-96f3319f3ff8.png)

**Comment by s-leger** [comment]
Draw tools are ment to actually "Draw" windows / doors over walls. You may create "standalone" windows / doors with the small button beside "Draw" tool in create tab.
While active the only way to move opening object is to mouse hover desired wall, then click to create window / door + hole.
Take a look at https://youtu.be/XChVewyZI1A
and https://youtube.com/stephen_leger/videos/
