### ISSUE TITLE
Can't install Archipack Pro

### ISSUE THREAD

**Issue by belac242** [s-leger/archipack#303]
Archipack version: 2.0.9

Blender version: 3.0.1

Os version: Mac OS 10.15.7

Description of the issue: 
<img width="936" alt="image" src="https://user-images.githubusercontent.com/24574699/154138936-cf33080d-3243-4a4e-b90b-5de7c70e9a32.png">

**Comment by s-leger** [comment]
You should find e-mail from blender-archipack.org with download link for latest version (2.4.0)
Once downloaded, setup over and restart blender.

**Comment by belac242** [comment]
That worked, thanks.
