### ISSUE TITLE
find problem in installing archipack pro in M1 Mac & tried with ubuntu as well but its not working.!

### ISSUE THREAD

**Issue by marliesilva** [s-leger/archipack#304]
Archipack version:20.9

Blender version:3.0

Os version: MAC M1

Description of the issue:find problem in installing archipack pro in M1 Mac & tried with ubuntu as well but its not working

**Comment by s-leger** [comment]
you should find a link to download latest version (2.4.0) in e-mail from blender-archipack.org
Download, ensure your browser did not uncompress the .zip file on the fly, setup over and restart blender.

**Comment by marliesilva** [comment]
S-leger,

thank you .. I received the email now from the support team..resolved it 💯
