### ISSUE TITLE
 Blender Crashes when updating archipack section.

### ISSUE THREAD

**Issue by JossyMath** [s-leger/archipack#313]
Archipack version: 2.4.0

Blender version: 3.1

Os version: Windows 10

Description of the issue: Every time I alight the Section lines to meshes, when I hit Update (to produce a cut section) in Archipack, Blender shuts down. Problem started in Blender3.0. How do I solve this?
![image](https://user-images.githubusercontent.com/76651747/160253582-a2072168-c86d-472c-9cd8-e1c272a06c9c.png)

**Comment by s-leger** [comment]
Fixed in 2.5
