### ISSUE TITLE
Unable to do a segment 

### ISSUE THREAD

**Issue by bedid** [s-leger/archipack#315]
Archipack version:
2.4.0
Blender version:
3.1.0
Os version:
12.3
Description of the issue:
When I try to clic on one of two arrows to create a segment , nothing happens , only a red color on the arrow but nothing . It could be very very difficult to do a wall.. Please if you have an idea... Thanks

**Comment by s-leger** [comment]
Use wall's draw tool instead, and if you exit the tool, you may restart by holding shift or alt and pressing the create button again.
