### ISSUE TITLE
I was charged the pro rate for the free version 

### ISSUE THREAD

**Issue by nosarious** [s-leger/archipack#317]
Archipack version:
2.0 (free version)

Blender version:

Os version:

Description of the issue:

When paying 5 pounds for the free version, the amount on the screen was for the price of the full version.

Can I get the full version since I inadvertently paid for it?

**Comment by s-leger** [comment]
As soon as an order for  pro version is made, archipack's server send an a-mail with download links.
Check your spam folder for e-mail from support@blender-archipack.org
