### ISSUE TITLE
Unable to add wall segments 

### ISSUE THREAD

**Issue by Woodenlamb** [s-leger/archipack#319]
Archipack version:2.4.0

Blender version:3.1.0

Os version:Mac OS 10.14.6

Description of the issue: Unable to add wall segments using white arrows. Tried using 'draw wall' function and holding shift to generate more segments but once the wall has been deselected this method stops working.

**Comment by IntegralExplorer** [comment]
Same issue here.
Archipack version: 2.4.0
Blender version: 3.1.2
macOS Big Sur version 11.6.5

I spent most of the day trying to follow Stephen's tutorial for adding a wall around my buildable area as a starting point and then tried the simpler CG Essentials tutorial when I was having trouble.

Here is how it behaves:
1. Add a wall and size it. Works fine.
2. Adjusted dimensions fine.
3. Going counter-clockwise (as per configuration) try to add a new wall segment by clicking on the white arrow. The arrow head turned red on mouse click, then white when release. Still only 1 segment. Nothing happens.
4. Then hit the "a" key to add (as per screen tip). Adds a wall but flips the orientation of the original wall 180 degrees from origin (thought it disappeared until I scrolled out). The new segment 2 was at the far, flipped end, but overlapped segment 1 with a slight angle. Modified the outer angle to be -90 degrees and then it rotated clockwise.
5. It appears that the segment numbering changed as well. The original vertical wall was renumbered to 2 and the new horizontal wall was 1. Although the whole thing could have been flipped on the x or y axis to create that impression.
6. Try to add a 3rd segment and it folds back on the first 2 segments and loses preset locations and angles.

At least that is as far as I can take it. Pretty confused but this appears to not be working as explained. Maybe novice mistake but have been trying many different combinations. I hope you can replicate and address.

**Comment by IntegralExplorer** [comment]
More info. Went to my Windows 10 computer and built a wall with Archipack 2.4.0 on the existing Blender 3.0.0 version. It worked fine.

Upgraded to Blender 3.1.2 and tried to build a wall. Had the same behavior as mentioned in my previous comment.

Temporary solution is to move down to Blender 3.0 and wait for the version of Archipack which addresses this issue.

But I want to say, thank you Stephen Leger for Archipack and the diligence you put in to keep up with the rapid growth of Blender. Your work is extremely valuable and strategic for unleashing architecture from proprietary constraints and opening up a myriad of creative solutions that we will see as Blender and BlenderBIM start getting a stronger foothold in the industry. So thank you for opening up the potential creative explosion from the community.

**Comment by IntegralExplorer** [comment]
More info: Down-versioned Blender 3.0.1 on Mac. ArchiPack worked as expected.

**Comment by famfuch** [comment]
same problem here. 3.1.2 and archipack 2.4.

**Comment by kostars1** [comment]
Same problem. Blender 3.1.2

**Comment by admelyssis** [comment]
Same problem here.
Blender 3.1.2
Archipack Pro 2.4.0
macOS 12.3.1
Given that 58€ is not exactly for free, this is a bit sad :(

**Comment by stemcgoo** [comment]
Same issue Blender 3.1.2

**Comment by s-leger** [comment]
Fixed in 2.5
