### ISSUE TITLE
Can't add Wall Segments

### ISSUE THREAD

**Issue by Shanetw26** [s-leger/archipack#323]
Archipack version: 2.4

Blender version:
3.1.2
Os version:
windows 10
Description of the issue:
Cant add wall segments after the first one

**Comment by s-leger** [comment]
You should rely on draw tool for walls under blender 3.1
https://youtu.be/JV3S84oDN0Y
Use shift or alt + press create button again to restart the tool when needed.

**Comment by s-leger** [comment]
Fixed in 2.5
