### ISSUE TITLE
Archipack 2.5.0 holes not cutting molding

### ISSUE THREAD

**Issue by BansheeSquad** [s-leger/archipack#328]
Archipack version: 2.5.0

Blender version: 3.2.0

Os version: Windows 10

Description of the issue: I have applied holes to walls throughout the model, and then floor molding to the walls. The holes are not cutting the floor molding. In the Hole > Shape tab I've got "Cut moldings" SELECTED ON. I scaled one of the holes wide to see if placing it outside the molding would create the cut but it did not affect the issue. Doors ARE cutting molding without issue.

![hole not cutting floorboard 01 220727](https://user-images.githubusercontent.com/88014484/181647723-bc6268c7-f158-47a9-bac1-ee4f0975c7a7.png)

![hole not cutting floorboard 02 220727](https://user-images.githubusercontent.com/88014484/181647771-d52411c5-78db-4755-89b8-11fa2ee2b157.png)

![hole not cutting floorboard 04 220727](https://user-images.githubusercontent.com/88014484/181647785-ce3203ec-629f-4c6f-b7ef-6420b823eb22.png)

**Comment by s-leger** [comment]
This is a known regression in 2.4 / 2.5, will be fixed in upcoming release.

**Comment by BansheeSquad** [comment]
Okay. Thanks for the update. Glad to know I'm not missing something.

**Comment by s-leger** [comment]
Fixed in 2.5.1
