### ISSUE TITLE
Archipack objects reset to shade smooth after every change

### ISSUE THREAD

**Issue by Sebride** [s-leger/archipack#334]
Archipack version:2.5.0

Blender version:3.3.0

Os version:MacOS 12.6

Description of the issue:
Whenever a new object is added (like a new window in a wall), the objects (windows, walls...) are set to shade smooth.
I need to manually set then back to shade flat individually.
Another modification, like opening a door, and the door is back to shade smooth.
This was not happening in previous versions.
I could not find a way to globally disable any AutoSmooth option.
Thanks

**Comment by Drill01** [comment]
Archipack version:2.5.0
Blender version:3.3.0
Os version:MacOS 13 (Beta)

I've been having the same issue with the shade smooth persistently appearing after every single operation.
I hope there will be a way to sort this out soon.
Thank you.

**Comment by s-leger** [comment]
This is a know issue related to api change in blender 3.3+, will be fixed in next release.

**Comment by Sebride** [comment]
Thank you. Good to know. Sorry for the doublon but  I could not find similar issue using keywords.

**Comment by s-leger** [comment]
Fixed in 2.5.1
