### ISSUE TITLE
Auto manipulate not working, no controls showing showing after creating wall segment or after selecting wall

### ISSUE THREAD

**Issue by quadcom** [s-leger/archipack#335]
Archipack version:2.50

Blender version:3.3.0

Os version: Win 10  21H1

Description of the issue: Automanipulate does not work. None of the controls show after creating a wall. I have to disabled 'auto' and manually click the manipulate button to bring the controls back on the screen

**Comment by s-leger** [comment]
Ensure that blender's "gizmos" are not disabled in properties of the 3d view (overlay button at top).
