### ISSUE TITLE
No Archipack menu under 'shift-A', only available under the 'N' flyout panel.

### ISSUE THREAD

**Issue by quadcom** [s-leger/archipack#336]
Archipack version:2.50

Blender version:3.3.0

Os version: Win 10 21H1

Description of the issue: There is no Archipack menu under the 'shift-A' create menu. All items need to be created from the Archipack 'N' menu flyout panel

**Comment by s-leger** [comment]
Archipack menu is under "mesh" category.
N panel is the way to go, as it does provide way more options (would make the "A" menu as long as 3 screens height)

**Comment by quadcom** [comment]
![image](https://user-images.githubusercontent.com/7085931/193486752-de800542-0b15-4082-a519-5ee324315a82.png)

**Comment by s-leger** [comment]
Unable to repro here (blender 3.3) any error in the console while loading the addon ?
![a_menu](https://user-images.githubusercontent.com/7442572/193487232-60884154-bdea-4bd5-b8cf-6326ef7b7a11.png)

**Comment by quadcom** [comment]
This is in the console at startup with no file loaded.



Read prefs: C:\Users\adrian\AppData\Roaming\Blender Foundation\Blender\3.3\config\userpref.blend
CAD Transform 0.93.2 : ready

----------------------------------------------

No module named 'blenderbim'
Archipack ifc export fallback
Archipack PRO 2.5.0 : ready

----------------------------------------------

botaniq is not installed in one of the default locations, please make sure the path is set in botaniq addon preferences!
register_class(...):
Warning: 'Cablecamrig' does not contain '_PT_' with prefix and suffix
Building Nodes: initialized
Writing userprefs: 'C:\Users\adrian\AppData\Roaming\Blender Foundation\Blender\3.3\config\userpref.blend' ok
Info: Preferences saved
Writing userprefs: 'C:\Users\adrian\AppData\Roaming\Blender Foundation\Blender\3.3\config\userpref.blend' ok
Info: Preferences saved
Writing userprefs: 'C:\Users\adrian\AppData\Roaming\Blender Foundation\Blender\3.3\config\userpref.blend' ok
Info: Preferences saved
Writing userprefs: 'C:\Users\adrian\AppData\Roaming\Blender Foundation\Blender\3.3\config\userpref.blend' ok
Info: Preferences saved
Writing userprefs: 'C:\Users\adrian\AppData\Roaming\Blender Foundation\Blender\3.3\config\userpref.blend' ok
Info: Preferences saved
Writing userprefs: 'C:\Users\adrian\AppData\Roaming\Blender Foundation\Blender\3.3\config\userpref.blend' ok
Info: Preferences saved
Writing userprefs: 'C:\Users\adrian\AppData\Roaming\Blender Foundation\Blender\3.3\config\userpref.blend' ok
Info: Preferences saved
Writing userprefs: 'C:\Users\adrian\AppData\Roaming\Blender Foundation\Blender\3.3\config\userpref.blend' ok
Info: Preferences saved
Writing userprefs: 'C:\Users\adrian\AppData\Roaming\Blender Foundation\Blender\3.3\config\userpref.blend' ok
Info: Preferences saved
Writing userprefs: 'C:\Users\adrian\AppData\Roaming\Blender Foundation\Blender\3.3\config\userpref.blend' ok
Info: Preferences saved
Writing userprefs: 'C:\Users\adrian\AppData\Roaming\Blender Foundation\Blender\3.3\config\userpref.blend' ok
Info: Preferences saved
Writing userprefs: 'C:\Users\adrian\AppData\Roaming\Blender Foundation\Blender\3.3\config\userpref.blend' ok
Info: Preferences saved

**Comment by quadcom** [comment]
![image](https://user-images.githubusercontent.com/7085931/193488173-39e812aa-aa03-48be-9fbb-81dbe485b12b.png)
