### ISSUE TITLE
faster wall creation

### ISSUE THREAD

**Issue by bliblubli** [s-leger/archipack#34]
Allowing to use custom orientation during the wall creation process would allow to quickly align walls to streets, other houses, etc. just by pressing for example X twice.

Using enter to confirm the whole stack would make it more consistent with other parts of Blender, making use of muscle memory while giving a way to completely abort operation with escape, which is faster compared to hitting backspace several time. Segments can be confirmed either with enter if length are entered with keybord or LMB if drawn freely with the mouse. Hitting enter if no length has been given confirms the stack.

Workflow would be: start operator, click to place starting point, hit chosen axis once for global twice for local axis, type length, confirm with enter, type length for next segment, enter, length, enter and again enter to confirm. 

Every step can be undone with backspace, tab can also be used to give precise values on x and y, shift enter at the end could close the wall by adding last segment.

**Comment by s-leger** [comment]
With notable exception of enter to confirm, those features are all implemented
