### ISSUE TITLE
Archipack will not enable after install.

### ISSUE THREAD

**Issue by Groovidge** [s-leger/archipack#341]
Archipack version: 20.9

Blender version: 3.31

Os version:  
![ARCHIPACK INSTALL ISSUE](https://user-images.githubusercontent.com/116769708/198156369-02f38603-b7c8-4547-8e33-a928e2d5f706.png)
Windows 10 Home
Version	21H1
Installed on	‎1/‎21/‎2022
OS build	19043.2130
Serial number	MJ0D645J
Experience	Windows Feature Experience Pack 120.2212.4180.0

Description of the issue: Archipack will not enable after installing.  Am new to this.  First paid addon to blender.

**Comment by s-leger** [comment]
You should find download link for latest version 2.5.1 in e-mail from support@blender-archipack.org
Once downloaded, setup over, restart blender and enable the addon.
