### ISSUE TITLE
Leaf tab edits do not apply to linked instances of an asset

### ISSUE THREAD

**Issue by tonygr1** [s-leger/archipack#349]
Archipack version: 2.5.1

Blender version: 3.3.1

Os version: Windows 11

Description of the issue:
Let's say you add a preset window to a wall in 3 places during same operation, then end. Now select one instance and go to Archipack. On Main tab, change the dimensions, and all 3 instances change to match. Now go to Leaf tab and for example, change the Window Leaf count from 2 to 1. The change only applies to the selected window and not all 3 instances.

**Comment by tonygr1** [comment]
The behavior only manifests for instanced objects (ex: Window) added during the same operation, but adding new instances of a saved preset works fine if the changed Leaf setting was saved with the preset

**Comment by s-leger** [comment]
Fixed in 2.6.0
