### ISSUE TITLE
Automatic floor molding doesn't close properly with door frames

### ISSUE THREAD

**Issue by jqhandres** [s-leger/archipack#350]
Archipack version: 2.5.1

Blender version: 3.1.0

Os version: Windows 10

Description of the issue: When I try to put moldings by selecting all the walls, the moldings doesn't fit perfectly on the door frames. I use custom walls and doors.
![unknown_2022 12 25-12 53](https://user-images.githubusercontent.com/121395465/209475157-036eec08-088a-45c3-a41e-ec8ba822287e.png)
![unknown_2022 12 25-12 54](https://user-images.githubusercontent.com/121395465/209475159-23d84e76-ea3b-47c5-bd0a-8068f269b6bf.png)

**Comment by XcydeDev** [comment]
Yes, we do have this problem too. Does not work properly since a few versions! We use a workaroud for this atm. would be great if this would get fixed soon.

**Comment by s-leger** [comment]
Solved in 2.6.0
