### ISSUE TITLE
Error :*(

### ISSUE THREAD

**Issue by cosplayzine** [s-leger/archipack#354]
Archipack version: 1.3.8

Blender version: 3.0

Os version: Windows 10 pro

Description of the issue: I am getting this error every time I try to install the addon. I have archi mech installed already and it has some errors of it's own. Such as I don't see a way to create a door and have it go through a mesh made (like a boolean) after making walls with the room from draw option. Sometimes room from draw only draws a partial wall and doesn't place place the room walls where i indicated. (I am in top view when creating it). Works only half the time. Sometimes blender will crash when using it. The Archipack won't install and I'm attempting directly from the official website. I watched a tutorial where he has both the create tab and the archimesh tab. I only have the create tab and with these limitations it doesn't seem super useable. The version of Archimesh I have installed is 1.2.3 with no option to remove it. I was debating on purchasing the full version but not sure if it will work giving the current errors I am having.
![image](https://user-images.githubusercontent.com/123426740/214181160-4032130b-c84c-4127-b8a8-143375325da6.png)

**Comment by s-leger** [comment]
Archipack 1.3.8 is an older release working only on blender 2.79
You may download archipack "community edition" (1.2.85) for blender 3.x using this link  https://gumroad.com/l/ZUrMf
