### ISSUE TITLE
Save Curtains/Binds Positions in Animation Keyframes

### ISSUE THREAD

**Issue by pihdastudios** [s-leger/archipack#355]
Archipack version:
2.5.1

Blender version:
3.4.1 flatpak

Os version:
Debian 11

Description of the issue:
I'm using archipack to create building for my upcoming game with interactive elements (opening doors, windows, curtains etc). Doors can be animated by rotating by its axis. Curtains and blinds cannot do that because it gets exported as a mesh and therefore cannot be opened and closed due to their nature of changing shapes.

One way of doing this is through animations. It would be nice if archipack can save curtains/blinds positions in keyframes.

Thank you.

**Comment by s-leger** [comment]
Curtain are animatable using "shape keys" values (in blender), dont know how this translate into your software by the exporter.

Blinds on the other hand are not, as it is impossible to handle properly using only linear translations, so such kind of animation would require to split mesh into many elements and animate each one according. I would avoid this in blender as it lead into performance issues when there are too many objects (starting at 10k+).
