### ISSUE TITLE
Error while trying to create ceiling, ceiling slab or roof

### ISSUE THREAD

**Issue by iiZags** [s-leger/archipack#356]
Archipack version: 2.5.1

Blender version: 3.4.1

Os version: Win 10

Description of the issue: Trying to create objects directly from wall.

Ceiling: 
Traceback (most recent call last):
  File "C:\Users\iZ\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\archipack_20\archipack_preset.py", line 427, in modal
    op('INVOKE_DEFAULT', **args)
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\modules\bpy\ops.py", line 111, in __call__
    ret = _op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
RuntimeError: Error: Error while building geometry: 'NoneType' object has no attribute 'name'

Error: Python: Traceback (most recent call last):
  File "C:\Users\iZ\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\archipack_20\archipack_preset.py", line 427, in modal
    op('INVOKE_DEFAULT', **args)
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\modules\bpy\ops.py", line 111, in __call__
    ret = _op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
RuntimeError: Error: Error while building geometry: 'NoneType' object has no attribute 'name'

Roof:
Error: Error while building geometry: 'NoneType' object has no attribute 'name'

Ceiling slab:
Error: Error while building geometry: 'NoneType' object has no attribute 'name'

The model can be found here:
https://drive.google.com/drive/folders/1gP1MxfVAzoejC22Nu1Q1pbaXVk3lBNUc?usp=sharing

I appreciate any help!

Thank you!!

iZags

**Comment by s-leger** [comment]
You must never edit a wall in blender's edit mode, and rely on wall's close attribute to actually properly close it.
Looks like there is no reference point (at least in shared file), leading to that error.
Use mail to support(at)blender-archipack.org for pro version support.

**Comment by iiZags** [comment]
Hi there! Thank you for your reply!
I have never edited the wall in edit mode. I did however deleted all the references. I looked everywhere to find out if it was needed to keep them and I couldn't find anything. 
So it's possible it's not working just because I've deleted the references?

I have the PRO version. Is it better to go through the support email next time?
 
Thank you!
