### ISSUE TITLE
Cannot enable

### ISSUE THREAD

**Issue by Snoiteandthesv3ndwarves** [s-leger/archipack#358]
Archipack version: 2.50

Blender version: 3.5b

Os version:MacOs 13.2.1

Description of the issue: Receive Shader compile error msg. Waiting for official release? Too early?

**Comment by s-leger** [comment]
Such kind of error probably occurs on blender's beta side and may be subject to daily change until release, so there is barely nothing i can do.

**Comment by s-leger** [comment]
Use "OpenGL" backed instead of "Metal" one in preferences->system.
