### ISSUE TITLE
Error Installing 

### ISSUE THREAD

**Issue by cesarstmartin** [s-leger/archipack#364]
Archipack version: Archipack 2.6.0

Blender version: Version 3.2.2 (3.2.2 2022-08-03)

Os version: Mac Os Monterrey 12.4 

Description of the issue: I can install it, but I get an error when I try to enable the add-on 
<img width="908" alt="Screen Shot 2023-04-05 at 3 10 02 PM" src="https://user-images.githubusercontent.com/129995677/230190778-bdba66cb-6ec8-4121-93b2-0c6005e9a612.png">

**Comment by cesarstmartin** [comment]
I updated to Blender 3.5 and is not working still

**Comment by s-leger** [comment]
You should find download link for latest version (2.6.0) in e.mail from support@blender-archipack.org.
Once downloaded (ensure your browser does not unzip on the fly or re-zip the folder) setup over, restart blender, then enable the addon.
Note that "Metal" backend still is not supported, so you must enable "OpenGl" backend in blender's preferences->system.
