### ISSUE TITLE
Error when trying to draw walls or add doors/windows etc etc

### ISSUE THREAD

**Issue by MortissCoffin** [s-leger/archipack#367]
Archipack version: Archipack PRO 2.0.9

Blender version: 2.93.4

Os version: Windows 8.1

Description of the issue:
![20230416_195019](https://user-images.githubusercontent.com/106203715/232351532-a350dd7c-98a9-42cc-80e2-34e02fe3800b.jpg)

**Comment by shivam124gg** [comment]
Not working

**Comment by s-leger** [comment]
You must download latest release using link in e-mail from support@blender-archipack.org
Once downloaded, setup over, restart blender then enable the addon.
