### ISSUE TITLE
Unreadable Fonts on all presets.

### ISSUE THREAD

**Issue by cpeppler01** [s-leger/archipack#369]
Archipack version: 2.6.0

Blender version: 3.5.1

Os version: Windows 10

Description of the issue: Unable to read the font that describes the presets.

To recreate:  
Create a new blender file.
Shift A -> Archipack -> Wall

![image](https://github.com/s-leger/archipack/assets/27712677/690bafd7-73c3-4eb0-81a8-5d4e4f072844)

**Comment by s-leger** [comment]
Increase preset thumbs size in addon preferences.
![prefs_thumbs](https://github.com/s-leger/archipack/assets/7442572/863611db-ec84-401c-80ab-0024ebe42f31)

**Comment by cpeppler01** [comment]
Perfect!  Thank you.  My apologies.  Please close, NOT_A_BUG
