### ISSUE TITLE
angle manipulators: slide and snap mode

### ISSUE THREAD

**Issue by bliblubli** [s-leger/archipack#37]
At the moment, changing an angle modifies the whole shape of the building. Often, it would help a lot to have the other end of the rotated wall to only slide along the next segment, to keep the rest of the wall shape the same. It would then work like the shear operator, but with the possibility to give exact angle.

Another helpful feature in architecture is the possibility to quickly orientate a wall segment to be parallel or perpendicular to another edge. Like the snapping method "align rotation to snapping target", but only for rotation.

**Comment by s-leger** [comment]
Upcomming 1.4 does implement bi-directional manipulators for size and angle, with more user friendly behaviour no more updating the whole shape of objects, but only manipulated segment and neighboors.
