### ISSUE TITLE
Material Rendering - Difference in surface offset between Eevee and Cycles

### ISSUE THREAD

**Issue by cpeppler01** [s-leger/archipack#371]
Archipack version: 2.6.0

Blender version: 3.5.1

Os version: Windows 10

GPU Config (Below)

Description of the issue: I brought in a material from Blenderkit that matches the look I wanted on a wall exterior.
I noticed that the material rendered as being offset from the actual surface of the wall mesh in a direction normal to the surface.
When switching between Eevee and Cycles, the problem only appeared in Cycles, but not in Eevee.  Below are images demonstrating
the issue:
Using Cycles:
![ArchipackCyclesRender](https://github.com/s-leger/archipack/assets/27712677/9574a7ad-87f7-4d50-a3ee-f8a471122b49)
Using Eevee:
![ArchipackEeveeRender](https://github.com/s-leger/archipack/assets/27712677/e2b6710e-c0a2-4827-a12b-924b644f76a6)
My GPU Configuration.  No change when switching between Optix and CUDA:
![GPUConfig](https://github.com/s-leger/archipack/assets/27712677/56718016-885f-4ad3-b71f-3b17ce58a412)

**Comment by s-leger** [comment]
Hi,
This is a shader specific issue with "displace" active.

**Comment by cpeppler01** [comment]
Thank you so much.  I apologize for the misplaced issue.  Based on your comment, I found the discrepancy in the shader, and fixed it.  Now working.  I am on a steep learning curve with Archipack, but it is an excellent piece of work.
