### ISSUE TITLE
Shader compile error

### ISSUE THREAD

**Issue by AntoineMetzger** [s-leger/archipack#378]
Archipack version: 2.6.0

Blender version: 3.6.1

Os version: Ventura 13.5

Description of the issue:
![image](https://github.com/s-leger/archipack/assets/141848671/3899f3b5-246b-45d7-bdc3-a92777b2125c)

**Comment by s-leger** [comment]
https://github.com/s-leger/archipack/issues/363#issuecomment-1491725456

**Comment by AntoineMetzger** [comment]
Bonjour,

Tout est Ok.

Merci
