### ISSUE TITLE
Can't enable Archipack

### ISSUE THREAD

**Issue by e49s2** [s-leger/archipack#380]
Archipack version: 1.3.8

Blender version: 3.6.4

Os version: windows 11

Description of the issue:
after installing archipack I try to enable it but he give me a error. Maybe because archipack is an older version than Blender. 
How can i fix it?

Thank you

this is the error
![archipack-error](https://github.com/s-leger/archipack/assets/146359498/9f8acc85-cea9-466d-90a5-7eeabc9bd8bb)

**Comment by s-leger** [comment]
Archipack 1.3.8 only work under blender 2.79

For a compatible version with blender 3.x

Community edition :
https://gumroad.com/l/ZUrMf

Pro version :
https://gum.co/ZRMyP

**Comment by e49s2** [comment]
Thank you
