### ISSUE TITLE
issue with walls and windows cut

### ISSUE THREAD

**Issue by Abdallahemad900** [s-leger/archipack#383]
Archipack version:2.6

Blender version: last

Os version:

Description of the issue: when i export wall with a window as glb the wall is not cuted in the middle in the place of the window
![Screenshot 2023-10-17 163832](https://github.com/s-leger/archipack/assets/73436692/ef4cd364-0ef9-488f-9236-b9f571005f20)
![Screenshot 2023-10-17 163732](https://github.com/s-leger/archipack/assets/73436692/95106a3b-bab9-42d8-b847-9024084b1cd0)

**Comment by s-leger** [comment]
User tools tab, apply holes before export.
