### ISSUE TITLE
cant activate 

### ISSUE THREAD

**Issue by sjm1959** [s-leger/archipack#388]
Archipack version:2.6.0

Blender version:4.0

Os version:
![Screenshot 2023-11-18 074058](https://github.com/s-leger/archipack/assets/38676962/3d570cb7-4d5f-4268-b3a9-706e972b4079)

Description of the issue:traceback

**Comment by s-leger** [comment]
Archipack 2.6.0 is not compatible with blender 4.0, you must wait for upcoming release, and rely on blender 3.x in the meantime.
