### ISSUE TITLE
Traceback error in Blender 4.0.2 on Windows 11 (archpack_2.0.9)

### ISSUE THREAD

**Issue by hakalachi** [s-leger/archipack#393]
Archipack version: 2.0.9

Blender version: 4.0.2

Os version: Windows 11

Description of the issue: 

![Archipack_Error](https://github.com/s-leger/archipack/assets/124232534/39027fcd-2d8a-4bd1-bb40-e0070b73fb47)

**Comment by hakalachi** [comment]
Closing issue - I received the correct version of the add-on that works with Blender 4+

**Comment by hakalachi** [comment]
Closing issue - I received the correct version of the add-on that works with Blender 4+

**Comment by clintcfavor** [comment]
Hi @hakalachi, may I ask what version you're currently using?

**Comment by hakalachi** [comment]
> Hi @hakalachi, may I ask what version you're currently using?

Blender version is 4.0.2
Working version of Archipack is 2.7.2
OS: Windows 11
