### ISSUE TITLE
Python error colorspace "Raw" not found

### ISSUE THREAD

**Issue by BoothIV** [s-leger/archipack#394]
Archipack version: 1.2.85

Blender version: 4.02

Os version: Win11

Description of the issue: Same issue as was once fixed already in the past: Archipack can not find Colorspace "Raw" and therefore displays an error message when trying to create an object. The error makes it impossible to create objects/use Archipack.

I only use Archipack to generate stairs but I really like the approach it offers. I can't find another tool for generating stairs that I'm happy with. I've had a look at the pro version but at this time I'm sure I don't need any of the other features. I was quite happy with the community edition and hope to be able to continue using it with Blender 4.x in the near future.

**Comment by s-leger** [comment]
Community edition is not compatible with blender 4.x
