### ISSUE TITLE
Issue installing Archipack 1.38 on Blender 3.1.2

### ISSUE THREAD

**Issue by MixMaxGitHub** [s-leger/archipack#396]
Archipack version: 1.38

Blender version: 3.1.2

Os version: Win11 Pro 64bit

Description of the issue:
![image](https://github.com/s-leger/archipack/assets/101669802/1c4ed724-2210-4597-b887-8947f1df6f81)

**Comment by s-leger** [comment]
1.3x series requires blender 2.79
