### ISSUE TITLE
Archpack Installation error

### ISSUE THREAD

**Issue by amulbhatia85** [s-leger/archipack#397]
Archipack version: 1.3.8

Blender version: 4.0

Os version: Windows 10.0.22621.3155

Description of the issue: Archipack not able to install as addon on blender , attach is the error

![error](https://github.com/s-leger/archipack/assets/8164464/62fcc6a5-2423-44f9-842a-cf05ff23a6e3)

**Comment by s-leger** [comment]
https://github.com/s-leger/archipack/issues/392#issuecomment-1884568393
