### ISSUE TITLE
Convert walls not working

### ISSUE THREAD

**Issue by mvital01** [s-leger/archipack#398]
Archipack version: 2.7.2

Blender version: 4.1

Os version: Mac OS 14.4.1 (23E224)

Description of the issue:
After creating several walls, I'd like to cobnert them to simple meshes, using the addon tools, but when I click in "merge", the walls simply blink and keeps measurements edit helpers. Am I doing anything wrong?

Thanks,
Marcelo Vital

**Comment by s-leger** [comment]
Merge walls is the opposite operation of "split", merging wall's ends into a single one.

If you want to create a single mesh from many walls, use "apply holes" and "kill parameters" for selection in the tools tab, but you'll no more be able to edit as archipack objects.
