### ISSUE TITLE
Archipack Pro Error on Enabling (Blender 4.0 /  Windows)

### ISSUE THREAD

**Issue by AliceInUeberland** [s-leger/archipack#399]
Archipack version: 2.6.0

Blender version:4.0

Os version:  22631 (W11 23H2)

Description of the issue:
Archipack is not showing up in blender anymore under "Mesh" (or at all except for under "Addons". When trying to re-activate or activate after re-install, the following error shows up:

![Archipack error](https://github.com/s-leger/archipack/assets/167033083/40fd5bc6-d9b5-4f41-ac3e-dcc7b68d5ddd)

Thank you for your help!

**Comment by mirzazeeshan435** [comment]
archipack is not working in blender .

**Comment by s-leger** [comment]
You must download latest release, 2.6.x is not compatible with blender 4.x
If you have any issue, please contact support through e-mail
