### ISSUE TITLE
Install of the Archipack script doesn't work 

### ISSUE THREAD

**Issue by siders** [s-leger/archipack#40]

**Comment by siders** [comment]
[
<img width="1794" alt="capture d ecran 2017-06-29 a 11 28 10" src="https://user-images.githubusercontent.com/12452770/27681692-637032f8-5cc0-11e7-9c8c-d81c4b9401bd.png">
](url)

**Comment by s-leger** [comment]
Checked and unable to repro under osx 10.10.5, Blender 2.78.

- Download zip from master branch.
- Choose downloaded zip as file to "install from file" in user preferences Add-ons
enabled without any trouble.
