### ISSUE TITLE
installation fails with blender 4.1 

### ISSUE THREAD

**Issue by epeter-** [s-leger/archipack#400]
Archipack version: 20-9

Blender version: 4.1

Os version: windows 11

Description of the issue:
![grafik](https://github.com/s-leger/archipack/assets/6928491/0699fd7c-0c2c-4543-9b0f-3f5d04e0414f)

**Comment by s-leger** [comment]
you must download latest release using link in e-mail from support@blender-archipack.org
once downloaded setup oover, restart blender then enable the addon.

**Comment by epeter-** [comment]
hi stephen, unfortunately i didn't receive an email from support@blender-archipack.org
(already checked if rated as junk)
