### ISSUE TITLE
onstallation fails with blender 4.0

### ISSUE THREAD

**Issue by epeter-** [s-leger/archipack#401]
Archipack version:20.0-9

Blender version:4.0

Os version: windows 11

Description of the issue:
![grafik](https://github.com/s-leger/archipack/assets/6928491/2ef413ae-8491-4e57-b8b8-0ffaf742a19a)

**Comment by s-leger** [comment]
you must download latest release using link in e-mail from support@blender-archipack.org
once downloaded setup oover, restart blender then enable the addon.
