### ISSUE TITLE
Pease Help me Fix this Issue as soon as posible

### ISSUE THREAD

**Issue by arain1234** [s-leger/archipack#403]
Archipack version:1.3.8

Blender version:4.1

Os version:Window 10

Description of the issue:
![Screenshot (7)](https://github.com/s-leger/archipack/assets/168711550/9c0ee555-0c97-465f-ac70-a952ea0aa6fa)

**Comment by s-leger** [comment]
Archipack "community edition" and 1.3.8 are not compatible with blender 4.x
