### ISSUE TITLE
Can not install Archipack  

### ISSUE THREAD

**Issue by Bereket-Derar** [s-leger/archipack#407]
Archipack version: 1.3.8

Blender version: 4.0

Os version: windows 10

Description of the issue: Can not install archipack once downloaded 
![Screenshot 2024-06-19 145728](https://github.com/s-leger/archipack/assets/145348158/d7c72337-175d-4f97-995f-80e4a544cb5a)

**Comment by s-leger** [comment]
See https://github.com/s-leger/archipack/issues/392#issuecomment-1884568393
