### ISSUE TITLE
Can not activate 

### ISSUE THREAD

**Issue by Bereket-Derar** [s-leger/archipack#408]
Archipack version: 1,3,8

Blender version: 4.0

Os version: Windows 11

Description of the issue: Can not activate Archipach after installing 
![Screenshot 2024-06-21 121416](https://github.com/s-leger/archipack/assets/145348158/42c61b24-5aca-4056-865b-7f3d99794441)

**Comment by s-leger** [comment]
https://github.com/s-leger/archipack/issues/392#issuecomment-1884568393
