### ISSUE TITLE
Blender crashes after checking Archipack addon

### ISSUE THREAD

**Issue by Ajax120** [s-leger/archipack#413]
Archipack version: 1.2.84

Blender version: 2.92

Os version: 6.8.0-44-generic

Description of the issue: whenever I check the box of the archipack addon in the preferences section, the blender app craches. And it's only happening when I check archipack, I've tried other addons and they work well. Please assist me there.

![archipack issue](https://github.com/user-attachments/assets/f4212d61-c036-4fec-be57-805dadb543d0)

**Comment by s-leger** [comment]
1.2.84 release is compatible with blender 2.7 - 2.8 series.
For blender 3.x series you must download from gumroad's store.
https://blender-archipack.gumroad.com/l/ZUrMf
