### ISSUE TITLE
Installation Issue - Archipack Add-on for Blender 4.3 - bgl.GL_LINE_STIPPLE Attribute Error

### ISSUE THREAD

**Issue by BlockchainMafia555** [s-leger/archipack#419]
Archipack version: 1.38

Blender version: 4.3

Os version: Windows 11 Pro

GPU : Intel (R) UHD Graphics

Description of the issue: I am experiencing an issue when attempting to install the Archipack add-on (version 1.38) on Blender 4.2. Upon installation, I encounter the following error message: 

Error: module 'bgl' has no attribute 'GL_LINE_STIPPLE'

**Comment by BlockchainMafia555** [comment]
![Screenshot 2024-12-08 175511](https://github.com/user-attachments/assets/39091056-7fa8-469e-ab25-1612b78d2fce)

**Comment by s-leger** [comment]
Archiupack  1.3.8 is compatible with blender 2.7x series only
