### ISSUE TITLE
Wrong Boolean

### ISSUE THREAD

**Issue by clintcfavor** [s-leger/archipack#43]
![image](https://user-images.githubusercontent.com/19337016/29350998-68fc2d14-8293-11e7-88f3-7f779883a348.png)

Hi Stephen,

A wall is taking the boolean from another wall. Screenshot above shows the wall without windows and doors, but is taking up the booleans from another building from different layer. Tried clicking the wall and added 1 window, but still taking up the booleans from the other building plus the 1 window I added. Could you lighten me up on this one? Pretty nice add-on btw. :)

**Comment by clintcfavor** [comment]
btw, the building from the other layer 
![image](https://user-images.githubusercontent.com/19337016/29351137-0d2609b4-8294-11e7-8b42-bfcb24d65f6a.png)

**Comment by s-leger** [comment]
Hi,
When you press "AutoBoolean", the tool look for holes into wall bounding box.
So if two buildings overlap, it dosen't know witch wall the hole belongs to.

Possible solution:
move the 1st building using the "Reference point" (A with arrow, parent of wall)
make the autoboolean, on both buildings, then move your reference point back, using "move to 2d" button on "Reference point" parameters.

**Comment by s-leger** [comment]
Fixed most boolean hole ownership issues using a real wall to hole intersection detection.
