### ISSUE TITLE
Preview images

### ISSUE THREAD

**Issue by carmelo81** [s-leger/archipack#45]
Hi, 
i tried this fantastic add-on but, when i try to add a object, do not showing any preview images. How to solve it?
Regards
Carmelo

**Comment by s-leger** [comment]
Hi,
Thumbs where not allowed in official disto, so made a tool to render them all at once (may take up to 5 min depending on your computer).

please take a look at https://github.com/s-leger/archipack/wiki/Archipack-Presets#rendering-thumbnails
Also take a look at https://github.com/s-leger/archipack/wiki/Setup 
for default material library setup.

**Comment by AaronH** [comment]
I have set things up as instructed and attempted to render the preview images.  After a couple of minutes the progress bar completes, but there are still no preview images (and the "render preview" button still has the triangle-! icon).

Currently trying to troubleshoot the issue, but I've attempted and restarted multiple times with no luck. 

(MacOS)

**Comment by AaronH** [comment]
After doing some additional testing it appears that on a Mac (running Sierra (10.12.6)) you must launch blender from the command line in order for the preview images to be saved. Even changing folder permissions inside the app was not a sufficient.  

No matter what else I try, preview images are only saved to the filesystem when launching Blender from the terminal.

**Comment by s-leger** [comment]
Hmm, 
you probably are facing with [osx path issue](https://developer.blender.org/rBS3d677d9190088aa7fe084767a39158a376cd5d63)   

Anyway, thank you for taking time to narrow down this issue !

As workaround, you may download the addon from this repository as i do provide thumbs pics - blender's repo policy dosen't apply here.

When you create new presets, the thumbs and preset are saved in user profile, so should no more need to change user permissions.

Best regards !

**Comment by s-leger** [comment]
Fixed, 
see [1.3.6+ documentation](https://s-leger.github.io/archipack/setup.html#activate-the-add-on)

**Comment by s-leger** [comment]
Revert back to an "out of the box" thumbs way to do, so now pics are available right after setup. (in unofficial version) as blender's policy for official addons dosen't apply here.
