### ISSUE TITLE
Colors on walls

### ISSUE THREAD

**Issue by Johnisland** [s-leger/archipack#50]
_Google traductor alert!_

I have created different rooms to which I want to give them different colors. But when selecting a color for the interior of the kitchen for example, that color is used on all walls of the house. What can I do to prevent this from happening? Thank you.

**Comment by s-leger** [comment]
Hi Johnisland,
Select your wall, then either make the material unique, create a new material, or assign another one.  
see [blender manual](https://docs.blender.org/manual/ko/dev/render/blender_render/materials/assigning_a_material.html)

**Comment by Johnisland** [comment]
Woooow It was easier than I thought ... I feel my ignorance, I have been using this program very little time. Thank you for your time, you saved my life! +1:

**Comment by s-leger** [comment]
From 1.4.0 wall will support material index as per segment, so i do close this issue.
