### ISSUE TITLE
Incomplete ad-on on Mac Sierra 10

### ISSUE THREAD

**Issue by Eliot33200** [s-leger/archipack#54]
Hi,
i tryed on W7 yesterday and it works (and it's great). On a Mac, just appears : AUTO BOOLEAN, RENDERING, and RENDERING PRESET in the tools menu.
The ad-on provides from the Blender's pack Mac.
An idea for fixing ?
Regard,

Eliot
<img width="293" alt="sc-10-13" src="https://user-images.githubusercontent.com/32760203/31532734-5a0b5b16-afef-11e7-96e1-51a3ee7313aa.png">

Blender version: 2.78
Os version: Sierra 10.12.6

**Comment by s-leger** [comment]
Hi,
by default, official addon add panels under "Tools" and "Create" tabs.
In order to change the panels location, go into preferences -> add-ons -> archipack -> "Tab category" and define the name of the tab for each panel.
