### ISSUE TITLE
blinds checkboxes doesn't seem to do anything?

### ISSUE THREAD

**Issue by zchana** [s-leger/archipack#60]
Description of the issue:
there are check boxes in components section of window panel which doesn't seem to work. Nothing changes when they are checked. They supposed to work like shutters, right? appear when activated along with some options to tweak?

Blender version:
2,79

Os version:
windows 10 64bit

**Comment by s-leger** [comment]
Unlike shutters, blind are standalone objects with many parameters,
simply select the blind itself to edit.
Checkbox in the window components parameters is only a convenient way to create / delete blinds.

see [blind documentation](https://s-leger.github.io/archipack/user/archipack%20objects.html#id26)

**Comment by zchana** [comment]
so this convenient way didn't work for me,
so I filled issue ..
nothing happens when I use checkboxes

**Comment by s-leger** [comment]
Thank you for reporting.
You're right, there is a bug in 1.3.6, window's update_blind use wrong arguments for archipack.blind() operator.
Will commit soon both fix for this issue and new kitchen generator in release 1.3.7, probably near end of this week.
