### ISSUE TITLE
Cant Clone the Wiki Git

### ISSUE THREAD

**Issue by Kobra299** [s-leger/archipack#62]
Description of the issue:

As the title suggests I m trying to download a copy of the wiki so I can read it offline but the link on the [https://github.com/s-leger/archipack/wiki](url) link does not seem to work 

https://github.com/s-leger/archipack.wiki.git does not seem to do anything just has errors

Blender version:
2.79

Os version:
Windows 7

**Comment by s-leger** [comment]
Hi,
archipack 1.3.7+(lastest)  [documentation download](/s-leger/archipack/archive/gh-pages.zip) 
archipack 1.2.8 wiki git download would require read rights and so git is likely to fail.
