### ISSUE TITLE
librairies lock the UI

### ISSUE THREAD

**Issue by mirlip** [s-leger/archipack#67]
Description of the issue: When clicking on an object type, the according library is opened. At this moment, to open another library, user has to press escape. It would be more user friendly to be able to switch just by clicking on another object type. It would also respect the non-blocking principle of Blender's UI.

**Comment by s-leger** [comment]
Hi,
Will take a look at a way to stop preset menu modal operator.
User may also close the menu using right click.

**Comment by mirlip** [comment]
The manipulators are modal operators and they allow to click on UI/menus, isn't it possible to do the same her (keep modal while keeping UI usable)?

**Comment by s-leger** [comment]
Manipulators are "PASS_THROUGH" so non blocking, 
making non blocking here is pretty simple, but have to find a reliable way to stop running preset modal when another one start.

**Comment by mirlip** [comment]
is there a way to identify if the click is made in the T panel or in the library area?

**Comment by s-leger** [comment]
First click might occur nearly everywhere on screen (N T panels and on screen when using shift+a menu)
Using release event will also kill starting one.
Using press event will kill old one after starting one.
Definitely need further investigations here.

**Comment by s-leger** [comment]
done though a global state variable

**Comment by bliblubli** [comment]
thank you for the quick fix :)
