### ISSUE TITLE
folder path for material library has no folder icon(to open a file browser)

### ISSUE THREAD

**Issue by mirlip** [s-leger/archipack#68]
a folder icon to open a file browser and from there choose the right folder would help a lot in many cases and would make it consistent with BlenderGIS for example.

**Comment by s-leger** [comment]
Thank you for this suggestion, i'll implement it as BlenderGIS does

**Comment by s-leger** [comment]
fixed, 
adding subtype="DIR_PATH"
to StringProperty does the trick

**Comment by mirlip** [comment]
Was fast, Thank you :)
