### ISSUE TITLE
slabs and floors update problem in 1.4

### ISSUE THREAD

**Issue by mirlip** [s-leger/archipack#69]
Description of the issue: After drawing a wall and creating slab from wall, 2 manipulators are active (one for the slab, one for the wall) and when trying to modify the angles with LMB, instead of grabing the angle arrows, it draws a selection rectangle. Even deactivating on or the other manipulator won't help. Both have to be removed and the one for the wall activated again for it to work. In this case the slab will be also updated, which is great, but if it's a floor instead of a slab, it won't update, even after the default 5sec.

Blender version: d59c2d12b12 (last week master) with left click select.

Os version: Arch Linux x64

**Comment by s-leger** [comment]
Wall auto-synch feature rely on hierarchy and only update childs of "reference point".
So always make a slab / windows / doors before the floor ensure floor will be child of reference point.

Unlike "Wall snap" and "DualSize" manipulators, "DualAngle" dosen't launch a transform.translate modal in the background, so it dosen't benefit of the "last one wins" order to capture events when multiple objects are manipulated.

I've added "alt+M" shortcut to start / end manipulate mode of current object. So use esc to exit all and then alt+M to restart.

**Comment by mirlip** [comment]
indeed, it works well with the slab. Slabs and floors are separated to allow different floors per flat? Maybe it would be possible nontheless to automatically add a slab if there is none yet, when adding a floor, to prevent the bug above and to allow free order of creation for the user.

Regarding the wall and slab with both manipulators, at least when the slab is created from the wall, I feel it would be easier to have only one manipulator for both.

The shortcut is cool :)

**Comment by s-leger** [comment]
Yes probably must add a reference point when adding either floor or moldings too (as for slabs/openings).
Slabs may include balcony, so overall shape may differs from floors, having two objects also allow different kind of floors for each interior space. 

Floor from wall create independant objects for each interior space, taking care of openings and slab cutters if any.

Might disable running manipulaors when creating new object, so only last one will be active.

**Comment by mirlip** [comment]
I find it cool actually to be able to manipulate different parts easily. Would it be possible to make the angle manipulators to work when several manipulators are running?

**Comment by s-leger** [comment]
Right click select does kill manipulators when you select any object, so there is always only a single one active at time. But i'm unable to share same behaviour with left select as left is in use to select manipulators handles.

Probably a "dumb" modal running on top of angle select could take focus and prevent events to bubble down the stack of other manipulators.
