### ISSUE TITLE
inner walls look outside

### ISSUE THREAD

**Issue by mirlip** [s-leger/archipack#71]
Description of the issue: When drawing the inner walls, clicking at the foot of the main wall make that archipack not always detect the wall we click on, resulting in a loose wall. To prevent this, it works to click a bit further, to ensure the new wall is bound to the main one, resulting in correct x/y orientation and in inner wall updating when modifying the main one. But it has a down side: the wall look outside, which makes visualization from outside buggy.
![room wall cuting](https://user-images.githubusercontent.com/12851284/38538955-52151b0c-3c96-11e8-9bc4-37d0b88ae2ac.png)

Would it be possible to make a join boolean so that the 2D plan and the exteriors visualization also look clean?

Blender version: all

Os version: all

**Comment by s-leger** [comment]
Boolean is not an option here, it is too weak to properly handle coplanar faces. Carve mode may crash blender.

Walls do have sides, should make a BI default material with different colors for each side so you are able to see the if inside is realy inside (outside is the "manipulable" side of wall).

In order for the draw a wall to "see" parent one, the mouse must hover parent. I know it could be difficult to snap that way.

T child walls currently only take care of orientation of the child wall first segment so y axis follow parent wall segment at create time. Only starting point does snap to parent, end point dosent, so you must use the "red placenolder" and snap point to locate end point of your child wall.

Could add another "Ray cast" detection for end segment, so when reaching another wall you press a shortcut with mouse over the other wall to "snap" end segment to hovered one. 

Relocate/auto-update dosen't require childs to actually be "T childs", they only must be child of reference point. So at this time not even sure T childs does make sense anymore.

**Comment by mirlip** [comment]
Would it be possible to reuse the code used to draw openings to position the wall? I mean instead of the world x,y under mouse cursor, take the x,y of the point of the wall the mouse is showing?

**Comment by s-leger** [comment]
Draw a wall allready share main "draw tools" code, and wall location works the same way than openings.
Wall creation only start one click after detection occured, as you should be able to setup first segment size / orientation - note that regular constraints does work at creation time (it is transform.translate based so share exact same behaviour, keyboard ability, snap, xy constraints in both local and global spaces). 
Windows and doors use prebuild model existing before first click as they wont require any further action.

**Comment by mirlip** [comment]
It works better now for the start point, but the end point is still flying.
By the way, drawing a wall makes the default cube smooth shaded.
