### ISSUE TITLE
"Kill Parameter Switch" missing from Tools Tab

### ISSUE THREAD

**Issue by WillsSch** [s-leger/archipack#73]
First of, thank you for this wonderful program. I love it!

Description of the issue:
For some reason I am not able to locate the kill parameter switch for a outer wall walls that I have made.. It seems that the version I update to in blender is the version 1.2.8, is that perhaps why?

Blender version:
2.79

Os version:
High Sierra
![screen shot 2018-05-14 at 22 26 50](https://user-images.githubusercontent.com/39270344/40003465-fb73102e-57c5-11e8-8524-d87cd856bce5.png)
![screen shot 2018-05-14 at 22 27 08](https://user-images.githubusercontent.com/39270344/40003467-fbbba596-57c5-11e8-9082-14d1eae2d5e1.png)

**Comment by s-leger** [comment]
Hi
Disable 1.2.8, save user preferences, and restart blender, then
Download and setup lastest one (1.3.8)
