### ISSUE TITLE
Blender crashes when trying to select a wall with a right mouse button click

### ISSUE THREAD

**Issue by xanderdin** [s-leger/archipack#75]
__Description of the issue:__

Blender crashes when trying to select a wall with a right mouse button click.

Tried with Archipack 1.3.8 and 1.2.8 with the same results.

__How to reproduce:__

1. Start Blender with default scene (with Cube).
2. Draw a Wall nearby.
3. Right click on the Cube to select it.
4. Right click on the Wall to select it -> Blender crashes.

Note: Blender does not crash when trying to select the wall in outliner tree.
Only when trying to select with a right mouse button click.

I'm including a sample file [wall.blend.zip](https://github.com/s-leger/archipack/files/2022452/wall.blend.zip). When I open this file Blender crashes on the second selection attempt, e.g.:

1. Open the file
2. Select the Cube
3. Select the Wall (no crash)
4. Select the Cube
5. Select the Wall (crash!!!)

Backtrace:

./blender(BLI_system_backtrace+0x20) [0x1a6c700]
./blender() [0x1078395]
/lib/x86_64-linux-gnu/libc.so.6(+0x33060) [0x7f2dc3f04060]
/usr/lib/x86_64-linux-gnu/dri/i965_dri.so(+0x1cab0a) [0x7f2da62d2b0a]
/usr/lib/x86_64-linux-gnu/dri/i965_dri.so(+0x1c83e9) [0x7f2da62d03e9]
/usr/lib/x86_64-linux-gnu/dri/i965_dri.so(+0x1be4d2) [0x7f2da62c64d2]
/usr/lib/x86_64-linux-gnu/dri/i965_dri.so(+0x1bdb12) [0x7f2da62c5b12]
/usr/lib/x86_64-linux-gnu/dri/i965_dri.so(+0x1a5d6f) [0x7f2da62add6f]
/usr/lib/x86_64-linux-gnu/dri/i965_dri.so(+0x1be202) [0x7f2da62c6202]
/usr/lib/x86_64-linux-gnu/dri/i965_dri.so(+0x3ada7e) [0x7f2da64b5a7e]
/usr/lib/x86_64-linux-gnu/dri/i965_dri.so(+0x1a1a60) [0x7f2da62a9a60]
/usr/lib/x86_64-linux-gnu/dri/i965_dri.so(+0x1a1ee9) [0x7f2da62a9ee9]
./blender() [0x176b7d4]
./blender() [0x1178069]
./blender(draw_object+0x1b93) [0x1185d93]
./blender(draw_object_select+0x31) [0x1187fb1]
./blender(ED_view3d_draw_select_loop+0x1c9) [0x1152199]
./blender(view3d_opengl_select+0x18e) [0x11719de]
./blender() [0x11682b0]
./blender() [0x116b285]
./blender() [0x116ba35]
./blender() [0x107fb09]
./blender() [0x1080f21]
./blender() [0x10815f8]
./blender() [0x1081958]
./blender(wm_event_do_handlers+0x507) [0x1081f97]
./blender(WM_main+0x18) [0x1078f78]
./blender(main+0x3f8) [0x1016a38]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf1) [0x7f2dc3ef12e1]
./blender() [0x10752ee]

__Blender version:__ 2.79b, fresh install without any custom user setup (only Archipack enabled)

__Os version:__ Debian GNU/Linux 9.4 (stretch) 64-bit
Debian GLIBC 2.24-11+deb9u3

**Comment by s-leger** [comment]
Hi, thank you for your report !

Was unable to repro under mac os. 
Dosen't have any debian based disto at this time to check.

Could it be that 1.2.8 was still active ? (eg without blender restart between 1.2.8 disable and 1.3.8 setup ? )

**Comment by xanderdin** [comment]
Hi!

No, 1.2.8 was disabled.

My first acquaintance with Archipack started with 1.3.8. I installed 1.3.8, enabled it and immediately encountered with the issue. Next, I tried to uninstall 1.3.8, then enabled 1.2.8 and got the same results. Then I completely removed all user configuration by deleting ~/.config/blender folder,
started Blender again, installed 1.3.8 again, and got the same crashes.

**Comment by s-leger** [comment]
Ok, 
currently trying to get someone else under debian based disto to see if we are able to repro your issue. Not at home those days so can't check myself asap.

**Comment by xanderdin** [comment]
Although I never experienced such crashes before using Archipack, it looks like
it is Blender and my hardware related issue, not Archipack's. Found similar issue at https://developer.blender.org/T52527.

Changing *Selection Method* to '**OpenGL Occlusion Queries**' under *User Preferences > System*
prevents Blender from crashes on wall selection.

Thanks!

**Comment by s-leger** [comment]
Thanks for reporting the solution for this nasty crash.
Hope you find archipack usefull for your work.
