### ISSUE TITLE
Dimension curve x-ray is not displayed

### ISSUE THREAD

**Issue by KUbo0** [s-leger/archipack#79]
Description of the issue: Dimension curve x-ray is not displayed
On the test below all the curves have x-ray
![result](https://user-images.githubusercontent.com/437009/41518782-eaf364f2-72cc-11e8-8c12-da32397954e4.png)
BezierCurve on the left was joined to Dimension, then separated
I could not figure it out myself
[Issue test scene](https://drive.google.com/open?id=1JDtTo8rQ-T8YmZpS5Zo02QFpqeTC2oKd)

Blender version: 2.79b

Os version: win10x64

**Comment by s-leger** [comment]
Archipack's objects use the flag
```python
object.show_transparent = True
```
to display material transparency on screen.

Select a dimension, the in the python console type
```python
C.object.show_transparent = False
```
