### ISSUE TITLE
Blender2.8Beta: Black window overlay without thumbs when adding objects to the scene.

### ISSUE THREAD

**Issue by catafest** [s-leger/archipack#88]
Description of the issue:
The add-on does not add objects to the scene from left panel.
I can add just a few objects with Shift+A key 
A strange window show me 
Blender version:
Blender 2.8 Beta 2018.12.08

Os version:
Windows 8.1

**Comment by s-leger** [comment]
Blender's official archipack addon require additional setup steps in order to work.
Preferences -> add-ons -> archipack -> "Setup actions" -> press "render thumbs"

**Comment by AyelGoth** [comment]
I confirm the error. Blender 2.8 does not allow to activate the plugin. When you try to activate the plugin, it launches an error message. This is the reason why when trying to create an object, the system does not allow it and throws the error. The error occurs when Blender 2.8 is updated to the latest beta version.
![screenshot_20190209_224713](https://user-images.githubusercontent.com/5136303/52528442-80a13380-2cbd-11e9-8410-6f8d0a2d6da2.png)

**Comment by s-leger** [comment]
Let me guess, you are on linux, probably build yourself (or setup through another location than bf), and missed the numpy module compilation - wich for whatever reason is not enabled by default.
So your issue is different one and related to the way you setup blender.

**Comment by jessePfammatter** [comment]
Thank you so much for your work on this great package! I too can confirm that objects (doors/windows0 can not be added from the left panel using the Blender 2.8 (Mac) and Archipack 1.2.81. Additionally, Archipack 1.3.8 fails to activate on my machine. I've attached several screenshots of the error messages. Thanks!
<img width="764" alt="screen shot 2019-02-20 at 8 52 21 am" src="https://user-images.githubusercontent.com/7946295/53102363-1b391800-34f1-11e9-9de8-04711d21ee9d.png">
<img width="649" alt="screen shot 2019-02-20 at 9 06 08 am" src="https://user-images.githubusercontent.com/7946295/53102364-1b391800-34f1-11e9-81c8-9b4ff19007b9.png">

**Comment by s-leger** [comment]
Archipack 1.3.8 does only work under blender 2.79b and is not compatible with 2.8
1.3.8 enhanced successor for 2.8 is version 2.x (commercial)

I was not able to repro your issue with 1.2.81 on windows/linux, could you share steps of your workflow ?

**Comment by jessePfammatter** [comment]
Thanks for the quick response!

I spent a little more time trouble shooting and it appears that I had the wall reference in a separate collection and hidden. So to get the above error I would select the wall, click add window/door in the toolbar, select style, and the error is produced when I try to place the object. No problem if all layers/objects are visible.

**Comment by jameskamel** [comment]
how do you apply it on apple?

**Comment by jameskamel** [comment]
i also get the black window overlay

**Comment by s-leger** [comment]
https://s-leger.github.io/archipack/setup.html#activate-the-add-on
