### ISSUE TITLE
Arckipack - not being able to resize

### ISSUE THREAD

**Issue by cmorandin** [s-leger/archipack#95]
Description of the issue:
When I try to edit the size of a window for example, I get a set of errors and it just doesn't work.

Blender version:
2.8

Os version:
Windows 10

![error](https://user-images.githubusercontent.com/30236291/52269275-843b6000-2935-11e9-9877-fa84df84e360.jpg)

**Comment by s-leger** [comment]
HI,
Thank you for reporting, this is a known issue and has been fixed in master.
https://developer.blender.org/rBAf1eda54f481169d89108353831ba1462cfb01411
