### ISSUE TITLE
Crashing when right clicking or esc to exit

### ISSUE THREAD

**Issue by thegaryishere** [s-leger/archipack#98]
Archipack version: 2.01

Blender version: 2.8

Os version: Win 10 pro

Description of the issue: Crashing when right clicking or esc to exit

**Comment by s-leger** [comment]
Any Hardops / boxcutter / kitops addon enabled ?

**Comment by thegaryishere** [comment]
I have KIT OPS enabled.

**Comment by s-leger** [comment]
There is a known issue with kitops / hardops / boxcutter (sharing same codebase) reported to authors. 
In the meantime you should disable those addons.

> masterxeon1001
> we just re-updated boxcutter and hard ops which should help with some of these errors.Checking into the kitops side of it.

**Comment by thegaryishere** [comment]
Thank you!

**Comment by Corretto9938** [comment]
I disabled Kitops, BoxCutter 7115_3(2.8), HOps 0097_6 Promethium (2.8)_2, FastCarve, and almost every other addon I had, but it still crashed right clicking or using escape.

So, I did a clean install and now adding windows, doors etc works.
Using todays 2.8 build.

**Comment by thegaryishere** [comment]
Downloaded latest KIT OPS PRO, and BLENDER 2.8. 
Archipack seems to be working fine now.

**Comment by s-leger** [comment]
Nice !
Thank you for reporting also when things get right  ;)

**Comment by thegaryishere** [comment]
Sorry , bad news...still crashes when adding doors...will try with windows...exiting from wall mode is fine. escaping from adding door definately crashes. Newest version on blender and KIT OPS PRO.
Any suggestions?

**Comment by thegaryishere** [comment]
Windows doing same thing, right clicking or esc , it crashes.

**Comment by thegaryishere** [comment]
disabled KITOPS PRO..fixed issue.. when enabled still crashing

**Comment by s-leger** [comment]
Good news, was able to narrow down and fix the issue with both kitops free and pro version.
Will probably push 2.0.2 middle of next week as i'm still hunting for another crash issue.
2.0.2 provide a new enhanced geographic Sunlight, fastest duplicate levels tool, and many bugfix including floors and moldings generation.
So stay tuned !

**Comment by thegaryishere** [comment]
Great news ! Thank you for the update!

**Comment by s-leger** [comment]
Fixed in archipack 2.0.2 release

**Comment by thegaryishere** [comment]
Thank you for the update. Seems to be working as expected so far. Will have more time to use next week.,
