### ISSUE TITLE
"Low poly" roman roof tile

### ISSUE THREAD

**Issue by corrado07** [s-leger/archipack#99]
Archipack version: 1.3.8

Blender version: 2.79.6

Os version: Win 10 x64

Description of the issue: Changing the size of the roof (especially with triangular ends option enabled) turns Roman roof tiles into kind of low poly mesh.

<img width="575" alt="cattura" src="https://user-images.githubusercontent.com/11272751/53284987-7ec67e00-375b-11e9-9ffa-6156f8c676d3.PNG">

Update: I separated the roof tiles from the main roof to add Bevel modifier manually and when i press C (clamp overlap) to avoid intersections it stops way before it is supposed to.

**Comment by s-leger** [comment]
it's a limitation of bevel, when tiles are cut on edges, this create some small faces making bevel fail that way.
I wanted to avoid high res tile model as every polygon must be checked when the code cut borders, and it may quickly take ages. 
You should enable auto smooth and increase the smoothing angle in the mesh normals parameters, and  use shade smooth on the base object.

**Comment by s-leger** [comment]
Changed bevel mode so it is no more clamped by smallest poly, but could lead to spikes.
If you encounter such issue, playing with amount may fix.

**Comment by abdelrahmanrefaie** [comment]
please, Do You have the code of C# Of that roof cladding. 

Thanks 
Avdelrahman Refaie 
weimar, germany

**Comment by s-leger** [comment]
Hi, 
here is python implementation
https://github.com/s-leger/archipack/blob/140_dev/archipack_roof.py#L1672

**Comment by abdelrahmanrefaie** [comment]
Many Thanks 
I appreciate that :D

**Comment by abdelrahmanrefaie** [comment]
sorry for disturbing you again, i didnt understand what u wrote in python because i dont know that language. can u give the idea briefly how to implement especiaaly in c# if you know 

i appreciate your understanding and thanks for your time

**Comment by s-leger** [comment]
Hi,
this code does rely on blender's api so the python side is by far not enough to make a standalone version. 
The final mesh is generated by blender's api calls and most matrix math too, geometry on the python side is in "degenerated state", single sided surface, without any volume to handle cuts, and i use blender's bmesh api to "solidify" the result.

Unfortunately i'm not familiar with c#
